### ISSUE TITLE
Resolver & Proto seem to depend unnecessarily on `futures-executor`

### ISSUE THREAD

**Issue by antonylsg** [bluejekyll/trust-dns#1002]
Hello,

It's my first issue. I hope to do it right.

It seems that Resolver and Proto depend on `futures-executor` but do not use it. So why not removing it from their dependency graph?

`futures` 0.3 uses `["std", "async-await", "executor"]` as default features, so we could replace:
```toml
futures = "0.3"
```
for both (Resolver and Proto) by:
```toml
futures = { version = "0.3", default-features = false, features = ["std"] }
```

It should slightly improve the compilation time.

**Comment by bluejekyll** [comment]
I think this was being used in tests at one point, but that may have change. If you’d like to submit a PR, and it passes CI then that would be enough of a test to prove that it’s no longer used there.

Thanks for the issue!
