### ISSUE TITLE
implment a dns response parser by trust-dns?

### ISSUE THREAD

**Issue by woodgear** [bluejekyll/trust-dns#1080]
hi, i'm try to implment a dns protocol parser. for now ,it use libpnet to capture all packet from 53,then i want to parse those packet by dns protocol, so i'm try to find a dns response parser, i think trust-dns should contain a dns response parser in some where,but i could not find where it is. am i have some missunderstand? or could give me some help about where should i dig.

**Comment by bluejekyll** [comment]
I think this is what you're probably looking for: https://docs.rs/trust-dns-proto/0.19.4/trust_dns_proto/op/message/struct.Message.html

Specifically this function: https://docs.rs/trust-dns-proto/0.19.4/trust_dns_proto/serialize/binary/trait.BinDecodable.html#method.from_bytes

**Comment by woodgear** [comment]
seems great, thanks.
