### ISSUE TITLE
[Resolver] use the system's dns conf, e.g. /etc/resolv.conf

### ISSUE THREAD

**Issue by bbigras** [bluejekyll/trust-dns#109]
Is there an helper or something to to a query using the system's dns servers that would also handle if the first one fails.

Right now it seems I need to hardcode the dns server ip.

**Comment by bluejekyll** [comment]
By "system" do you mean read /etc/resolv.conf or equivalent?

**Comment by bbigras** [comment]
Yes.

**Comment by bluejekyll** [comment]
This is something I plan to include in the Resolver. I thought I had an issue open for that, but I didn't, so I opened a new one: #110 

Basically, the Client is supposed to be a dumb DNS client. I decided this after some concerns around the DNSSec solving logic, which will probably migrate to the Resolver package in time. I plan on starting this work after I finish some work on mTLS.

**Comment by bluejekyll** [comment]
Depends on #110

**Comment by bluejekyll** [comment]
see #136 

I plan for that to support reading the system resolv.conf
