### ISSUE TITLE
Too many open files (os error 24) using multiple resolver instances

### ISSUE THREAD

**Issue by Edu4rdSHL** [bluejekyll/trust-dns#1097]
**Describe the bug**
I'm having the problem `Too many open files` when creating a resolver from parts using https://docs.rs/trust-dns-resolver/0.19.5/trust_dns_resolver/struct.Resolver.html. I'm sing the following code:

```rust
pub fn get_resolver(resolvers_ips: &Vec<Ipv4Addr>, opts: &ResolverOpts) -> Resolver {
    match Resolver::new(
        ResolverConfig::from_parts(
            None,
            vec![],
            NameServerConfigGroup::from_ips_clear(
                &[IpAddr::V4(
                    resolvers_ips[rand::thread_rng().gen_range(0, resolvers_ips.len())].clone(),
                )],
                53,
            ),
        ),
        *opts,
    ) {
        Ok(resolver) => resolver, 
        Err(e) => {
            error!("Failed to create the resolver. Error: {}\n", e);
            std::process::exit(1)
        }
    }
}
```

**To Reproduce**
I call the get_resolver() function everytime I need to do a lookup. The idea is mainly that we use a list of resolver IPs and they are picked randomly.

I suspect that the problem is the `Resolver::new`, `ResolverConfig::from_parts`
 and `NameServerConfigGroup::from_ips_clear` calls everytime. Is there an option to just change the resolver IP? That will avoid the need to create a new resolver everytime but just use references.

**Expected behavior**
No `Too many open files (os error 24)` error.

**System:**
 - OS: ArchLinux
 - Architecture: x86_64
 - Version: Not apply.
 - rustc version: 1.42.0

**Version:**
Crate: [Resolver](https://docs.rs/trust-dns-resolver/0.19.5/trust_dns_resolver/struct.Resolver.html)
Version: 0.19.5

**Additional context**
The number of resolvers created are up to 500.

**Comment by bluejekyll** [comment]
Is the Resolver being dropped (either directly or by going out of scope) between each call of grt_resolver?

**Comment by Edu4rdSHL** [comment]
Hey @bluejekyll, thank you for your quick response. This was just a problem with the OS configuration having a very low number of open files limit.

Closing and sorry.
