### ISSUE TITLE
Use res_init to obtain unix DNS configurations?

### ISSUE THREAD

**Issue by Mygod** [bluejekyll/trust-dns#1099]
`/etc/resolver.conf` might not be the best way to do this, e.g. Android does not have this file. Perhaps we could try to use `res_init` or `res_ninit` as per [this answer](https://stackoverflow.com/a/4251093/2245107)?

**Comment by bluejekyll** [comment]
Seems reasonable. I'm not sure if we want this across the board, but clearly for Android this would be a good change.

Trust-DNS used to have internal parsing logic for resolv.conf, but that was all migrated to the `resolv-conf` crate. My suggestion is that we either put an FFI into that crate, or create a new separate crate that returns the same structures as the `resolv-conf` crate.

I'd be happy for us to integrate this for Android initially, and then see about using it at some point in the future across more OSes.

**Comment by Mygod** [comment]
Another thing to take into consideration is that DNS nameservers are subject to change, _especially_ on a mobile device (disconnecting from a Wi-Fi might cause the device to use another nameserver). Android has a [native async resolve API](https://developer.android.com/ndk/reference/group/networking#group___networking_1ga4faf1bb0d7fd38c2153eebefcfb8f056), but that was only added in Android 10. This `res_init` approach might be preferable for legacy versions.

**Comment by bluejekyll** [comment]
Yes, we don't currently have a strong design around the dynamic nature of DNS configuration on mobile (or less frequently laptops). It is something that we should support, at the moment, it would require a new resolver to be constructed on configuration changes.

I'm assuming `res_init` will change upon any change to DNS configuration at the OS level.

**Comment by Mygod** [comment]
Well I have [bad news](https://thesquareplanet.com/blog/the-story-of-a-rust-bug/) for you...

**Comment by bluejekyll** [comment]
What's the bad news? that's all stdlib related, isn't it? res_init has FFI in libc, should be exposed on Android, isn't that the start to what we want?

**Comment by Mygod** [comment]
Oh the point is that `res_init` seems to cache system resolver configuration at the time of invocation instead.

**Comment by bluejekyll** [comment]
Ah. I see.

**Comment by Mygod** [comment]
Looks like [`res_ninit` is buggy as well](https://stackoverflow.com/q/49579030/2245107). We should stick to current implementation perhaps.
