### ISSUE TITLE
Feature: Resolver, add trust-dns-resolver

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#110]
This would be a full resolver that could be used instead of a system resolver.

**Comment by bluejekyll** [comment]
see #136

**Comment by msehnout** [comment]
It would be nice to have something like [dnssec-trigger](https://www.nlnetlabs.nl/projects/dnssec-trigger/) that could be used with trust-dns-resolver. I'm using dnssec-trigger for validation on my laptop and it kind of works, but it'd be nice to have project with more welcoming upstream and not written in plain C.

**Comment by bluejekyll** [comment]
What do you use dnssec-trigger for? It looks like it validates DNSSec RRSIGs if I understood the about page.  TRust-DNS does already support this. For the resolver it will just be a matter of swapping in the validating when creating a resolver. I'll try and make sure I have examples for this.

**Comment by msehnout** [comment]
dnssec-trigger itself is used just to configure unbound resolver according to my network configuration. It works something like this:
When I connect to a network, NetworkManager has a hook that will send network configuration to dnssec-trigger. 
Dnssec-trigger then performs a probing, which means it tries to use DHCP provided resolvers for DNSSec validation.
Then it configures Unbound resolver according to probe results. It should configure unbound in such a way, that internal queries are not sent outside of a corporate network and ideally it should also send reverse queries to the proper resolver.

I hope this explanation is not completely messed up. For more information you can check out this Fedora wiki page:
https://fedoraproject.org/wiki/Networking/NameResolution/DNSSEC

**Comment by bluejekyll** [comment]
FYI, I just landed this feature in master. I'll be publishing a crate in the next few days.

For the feature you mentioned above. I'm not sure it's something that I will necessarily work on, but if you want to create an issue for it, we can track it and see if anyone else is interested in that?
