### ISSUE TITLE
Documentation bug in crate.io

### ISSUE THREAD

**Issue by jannewmarch** [bluejekyll/trust-dns#1101]
The example use on crate.io for turst-dns-resolver v0.19.5 has the line
let address = response.next().expect("no addresses returned!");
it should be 
let address = response.iter().next().expect("no addresses returned!");

**Comment by bluejekyll** [comment]
Oops! If you have some time, feel free to submit at PR.

**Comment by muskuloes** [comment]
Hi I just submitted a PR for this :)

**Comment by bluejekyll** [comment]
Fixed in  #1108
