### ISSUE TITLE
Mutable access to `Message` members

### ISSUE THREAD

**Issue by leshow** [bluejekyll/trust-dns#1117]
I'd like to mutate a field in the `answers` vec of a Message. Is there a reason why `take_*` is the only available way to do that? Right now the only way to change entries in a `Message` that I can see is to `take` them, which causes an allocation, then mutate and replace them again.

I'd be happy to submit a PR for something like `answers_mut` that returns a `&mut Vec` if that's amenable to you?

**Comment by bluejekyll** [comment]
I don't think there is any reason why that doesn't exist, and should be fine to add. I can only guess that based on my own usage, it was always building a message up, and never changing or swapping components.

Feel free to add the API, we should probably do the same for `additionals` and `name_servers` sections as well, right?

**Comment by leshow** [comment]
Sounds good to me!

The particular use case we're running into is that we are getting a response from a dns forwarder and want to modify the ttl of the results. 

I'll add the respective methods to the other bits also
