### ISSUE TITLE
Parsing EDNS OPT fails with zero length option

### ISSUE THREAD

**Issue by TheEnbyperor** [bluejekyll/trust-dns#1138]
**Describe the bug**
A EDNS option with zero length will fail parsing.

**To Reproduce**
DIG with `+nsid` option.
Generates the warning that follows:
` WARN  trust_dns_proto::rr::rdata::opt > incomplete or poorly formatted EDNS options: Data { code: NSID, length: 0, collected: [0, 10, 0, 8, 34, 143, 97, 69, 174, 26, 243, 49] }`

**Expected behavior**
Parsing the NSID as present and of zero length.

**System:**
 - OS: Nixos
 - Architecture: x86_64
 - Version: N/A
 - rustc version: 1.44.0-nightly (dbf8b6bf1 2020-04-19)

**Version:**
Crate: proto
Version: 0.19

**Additional context**
Problem appears to be around [line 238 in rr:rdata::opt](https://github.com/bluejekyll/trust-dns/blob/master/crates/proto/src/rr/rdata/opt.rs#L238)

**Comment by bluejekyll** [comment]
There is a stalled PR to deficit this: #744

Not sure what the state of that is.

**Comment by TheEnbyperor** [comment]
Ah excellent, will verify this actually fixes it sometime this week.
