### ISSUE TITLE
Thread 'test_server:udp:server' panic

### ISSUE THREAD

**Issue by liranringel** [bluejekyll/trust-dns#114]
The test `test_server_www_udp` seems to leak the thread called `test_server:udp:server` and panic with that error:
> thread 'test_server:udp:server' panicked at 'cannot create new TLS keys after the main thread has exited', C:\bot\slave\stable-dist-rustc-win-msvc-64\build\src\libstd\sys\windows\thread_local.rs:143

First occurred to me in appveyor, and I'm able to reproduce it on my local windows machine:
https://ci.appveyor.com/project/liran-ringel/trust-dns/build/1.0.4/job/33yskkn020b6ec0p

**Comment by bluejekyll** [comment]
Huh. I haven't noticed that anywhere else. Do you have a back trace possibly?

**Comment by liranringel** [comment]
When I don't set RUST_BACKTRACE=1, It stuck.
When I do set RUST_BACKTRACE=1, It just print that the panic happened, but does not display the backtrace.
Then I thought I need to pass `--nocapture`, but when I do that, It doesn't panic at all.

**Comment by bluejekyll** [comment]
Sounds like a race condition. I don't think I'm doing anything crazy there, so I wonder if there is a bug in the library.

**Comment by liranringel** [comment]
Is that ok that the thread called `test_server:udp:server` is not joined? Threads are detached when `JoinHandle` is dropped.

**Comment by liranringel** [comment]
Ok I set a breakpoint on `panic_unwind::__rust_start_panic` with windbg, that's the backtrace:
https://gist.github.com/liranringel/ac938f20e6beecf4b5182013460440dd

**Comment by bluejekyll** [comment]
Woh. I totally misread the docs on that. That's a good catch. I should definitely be joining both threads.

**Comment by bluejekyll** [comment]
Not sure why it's a problem on windows though. It's only a few threads, and all should be cleaned up on process exit.

**Comment by bluejekyll** [comment]
Never mind. Now I'm more confused as to why I have seen this on Linux or macOS. Anyway, I'll look at a patch tonight. Should I set up an app auto account to connect to this?

**Comment by liranringel** [comment]
Sorry I didn't understand the last question.

According to the backtrace, the panic is raised here: https://github.com/rust-lang/rust/blob/master/src/libstd/sys/windows/thread_local.rs#L69

It happens because `TlsAlloc()` returns `TLS_OUT_OF_INDEXES` (https://msdn.microsoft.com/en-us/library/windows/desktop/ms686801(v=vs.85).aspx).
That article says that TLS (thread-local storage) has a limit on windows:
https://msdn.microsoft.com/en-us/library/ms686749(VS.85).aspx
as opposed to linux: http://stackoverflow.com/a/1461048
So if there is a leak of the thread-local storage, it can explain why it happens only on windows.

**Comment by bluejekyll** [comment]
Thanks for the links. I guess the reason I'm confused is because the number of connections even with the leak (which we should fix) should only be 6 or so. But anyway, I'll get a fix in for the thread join.
