### ISSUE TITLE
Support mDNS cache-flush bit

### ISSUE THREAD

**Issue by fluxxu** [bluejekyll/trust-dns#1142]
I am trying to use trust-dns's types to manually deserialize some mDNS messages. It seems that currently, the  BinDecodable of Record doesn't handle cache-flush bit(https://tools.ietf.org/html/rfc6762#section-10.2). It this bit is set, the deserialize will fail with DNS class value unknown: 32769 (DNSClass::IN with cache-flush bit set).

I tried to make a PR for this. But I'm not sure what is the correct way to do it. I can detect this bit in `impl BinDecodable` of `Record` but this bit only relevant to mDNS record. Or maybe I can change `DNSClass::from_u16` to decode all unknown value as `DNSClass::OPT`. 😵

**Comment by bluejekyll** [comment]
I can't find the value `32769` referenced anywhere in the documentation. Not sure why I'm missing it.

In terms of support we should add the `DNSClass` enum, `CacheFlush` (open to other names, like `MdnsCacheFlush`), and document that this should only be used in the context of an mDNS request.

I think that seems like the correct thing to do, based on the docs.

The feature flag `#cfg(feature = "mdns")` is available in the proto crate, and this can be used to enable/disable the enum field, only allowing it with mDNS enabled.

**Comment by fluxxu** [comment]
>I can't find the value 32769 referenced anywhere in the documentation. Not sure why I'm missing it.

You can search `0x8001` then there is a paragraph about this value:
```
   Note that the cache-flush bit is NOT part of the resource record
   class.  The cache-flush bit is the most significant bit of the second
   16-bit word of a resource record in a Resource Record Section of a
   Multicast DNS message (the field conventionally referred to as the
   rrclass field), and the actual resource record class is the least
   significant fifteen bits of this field.  There is no Multicast DNS
   resource record class 0x8001.  The value 0x8001 in the rrclass field
   of a resource record in a Multicast DNS response message indicates a
   resource record with class 1, with the cache-flush bit set.  When
   receiving a resource record with the cache-flush bit set,
   implementations should take care to mask off that bit before storing
   the resource record in memory, or otherwise ensure that it is given
   the correct semantic interpretation.
```
As I understand it, this bit is an additional property to [`proto::re::resource::Record`](https://github.com/bluejekyll/trust-dns/blob/main/crates/proto/src/rr/resource.rs#L69) struct. I guess we should still use `DNSClass::IN` as the dns class value.
I propose to add a `mdns_cache_flush: bool` to the struct. We can detect the bit, set `mdns_cahce_flush`, then set dns class with that bit removed.
