### ISSUE TITLE
How to get CNAME records?

### ISSUE THREAD

**Issue by Edu4rdSHL** [bluejekyll/trust-dns#1152]
I have been using [trust_dns_resolver](https://docs.rs/trust-dns-resolver/0.19.5/trust_dns_resolver/) for a while, now I need to get the CNAME record of the host but I didn't found a way for it, not examples in the documentation and nothing at all searching by "CNAME". Additionally according to [this document](https://docs.rs/trust-dns-resolver/0.19.5/trust_dns_resolver/lookup/index.html) there is not way to perform a CNAME lookup but the initial page says that CNAME lookups are supported.

Regards,
Eduard

**Comment by bluejekyll** [comment]
You'll want this method: `https://docs.rs/trust-dns-resolver/0.19.5/trust_dns_resolver/struct.AsyncResolver.html#method.lookup` and pass in the record type of CNAME. Have you tried that?

**Comment by Edu4rdSHL** [comment]
Thank you, this worked. Now I have the following data:
```
Lookup { query: Query { name: Name { is_fqdn: true, labels: [blog, securityhacklabs, net] }, query_type: CNAME, query_class: IN }, records: [Record { name_labels: Name { is_fqdn: true, labels: [blog, securityhacklabs, net] }, rr_type: CNAME, dns_class: IN, ttl: 3, rdata: CNAME(Name { is_fqdn: true, labels: [ghs, google, com] }) }], valid_until: Instant { tv_sec: 21101, tv_nsec: 925270204 } }
```
How can I access to the CNAME labels in a valid format (String or str)? In this case should be `ghs.google.com`. I appreciate if you can help me with that, otherwise feel free to close the issue since that I have the CNAME records data.

**Comment by bluejekyll** [comment]
roughly, you want something along these lines:

```rust
let lookup = resolver...;

let name_strs: Vec<String> = lookup
    .iter()
    .filter_map(|rdata| rdata.as_cname())
    .map(|name| name.to_string())
    .collect();
```

**Comment by Edu4rdSHL** [comment]
Thank you a lot, @bluejekyll!
