### ISSUE TITLE
Cannot resolve multiple record types concurrently

### ISSUE THREAD

**Issue by pabloparada** [bluejekyll/trust-dns#1174]
**Describe the bug**
Name resolution fails when executing lookup for records of different types.

**To Reproduce**
Lookup records of type `TXT` and `SRV`.

**Expected behavior**
Multiple calls to resolver functions `Resolver::srv_lookup` and `Resolver::txt_lookup` should successfully resolve a name.

**System:**
 - OS: Manjaro
 - Architecture: x64
 - Version 20.0.1
 - rustc version: 1.45

**Version:**
Crate: trust-dns-resolver
Version: 0.19.5

**Additional context**
Downgrading to version 0.18.1 works well.

```
thread 'resolver::test::test' panicked at 'called `Result::unwrap()` on an `Err` value: ResolveError { kind: NoRecordsFound { query: Query { name: Name { is_fqdn: false, labels: [mongo-shd] }, query_type: SRV, query_class: IN }, valid_until: Some(Instant { tv_sec: 118525, tv_nsec: 559938142 }) }, backtrack: None }', core/src/resolver.rs:74:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by bluejekyll** [comment]
I think this is fixed in `main`. I want to publish a preview release soon for that.

**Comment by pabloparada** [comment]
Thank you very much!

**Comment by bluejekyll** [comment]
@pabloparada would you be able to verify this in the `0.20.0-alpha.1` release?

**Comment by pabloparada** [comment]
I can't @bluejekyll, have no access to related source anymore, sorry :(

**Comment by pabloparada** [comment]
Hey @bluejekyll I've wrote a small test just to check and give you feedback and seems to work perfect! Thank you again!

**Comment by bluejekyll** [comment]
Thank you for confirming!
