### ISSUE TITLE
Name compression failures on corner cases

### ISSUE THREAD

**Issue by jacoblin1994** [bluejekyll/trust-dns#1179]
**Describe the bug**
Name compression seems to fail on some corner cases, in this case, 'frontdoor.nest.com.' followed by several of its answer records 'frontdoor-srt01-production-1909587911.us-east-1.elb.amazonaws.com.' Strangely enough, if you swap the order presented to BinEncoder such that 'frontdoor.nest.com.' is placed at the end, the compression seems to be done correctly as expected.

**To Reproduce**
[trust-dns/crates/proto/src/rr/domain/name.rs](https://github.com/bluejekyll/trust-dns/blob/16f4e862ef158972967ab738c86d567d2938d899/crates/proto/src/rr/domain/name.rs)

    #[test]
    fn test_pointer() {
        let mut bytes: Vec<u8> = Vec::with_capacity(512);

        let first = Name::from_str("frontdoor.nest.com.").unwrap();
        let second = Name::from_str("frontdoor-srt01-production-1909587911.us-east-1.elb.amazonaws.com.").unwrap();
        let third = second.clone();

        {
            let mut e = BinEncoder::new(&mut bytes);

            first.emit(&mut e).unwrap();
            assert_eq!(e.len(), 20);

            second.emit(&mut e).unwrap();
            assert_eq!(e.len(), 84);

            third.emit(&mut e).unwrap();
            assert_eq!(e.len(), 86); // Should be 86 but get 148 instead that adds another 64 bytes
        }
    }

**Expected behavior**
Expect Name/labels to be properly compressed but the result does not seem to suggest so.

**Version:**
Version: [0.7.3]

**Comment by bluejekyll** [comment]
woh. 0.7? is there a reason you're using such an old version?

There were some label compression issues in earlier releases, but current versions should be working correctly.

**Comment by jacoblin1994** [comment]
Thank you, Benjamin, for the reply.

I also did the testing on the latest version 0.19.5 as well, which is failing as well. This compression method, [emit_as_canonical](https://github.com/bluejekyll/trust-dns/blob/16f4e862ef158972967ab738c86d567d2938d899/crates/proto/src/rr/domain/name.rs#L587), has been untouched for the past 3 years or so if I understand it correctly. Could you please confirm if you are able to compress appropriately on the above specific queries?

**Comment by bluejekyll** [comment]
It’s been a while since I’ve looked at this. It’s quite possible the logic hasn’t changed in 3 years.

I haven’t spent a ton of time optimizing the label compression, so it wouldn’t surprise me if there are some improvements available in this area.

**Comment by bluejekyll** [comment]
Looking at this a little more, I think the issue here is that we're not picking the best label compression option, only the first found. It feels like we should have two passes here rather than the single one that is happening today. Basically, search through all the labels, and look for the longest matching one.

**Comment by jacoblin1994** [comment]
It looks like trust-dns-proto does not support labels ending with a pointer compression as in encoder.trim(), the associated name_pointers get removed completely due to the new offset being set.
https://tools.ietf.org/html/rfc1035#section-4.1.4

**Comment by bluejekyll** [comment]
That's definitely possible. Again, this needs to be optimized, and that hasn't happened. The code clarity in this area could be improved as well.

If you were interested in working on this, I'd definitely love the help.

**Comment by jacoblin1994** [comment]
Thanks Benjamin. Happy to help with this.

I do have a working patch that I still want to take some time polishing.

**Comment by jacoblin1994** [comment]
Hi Benjamin, could you please add me as a collaborator, so that I can make a pull request? Thanks.

**Comment by bluejekyll** [comment]
Usually folks fork the repo in Github, and then submit PRs from their fork in Github, that doesn't require collaborator status: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by jacoblin1994** [comment]
Sounds good. I will follow this. Thanks.
