### ISSUE TITLE
Ability to modify queries

### ISSUE THREAD

**Issue by leshow** [bluejekyll/trust-dns#1194]
I'm happy to write a PR for this if it's something you'd consider accepting, just let me know how you'd like to do it

**Is your feature request related to a problem? Please describe.**
I have a need to remove a query from a `Message` and replace it with another

**Describe the solution you'd like**
Mutable access to the queries field would work, or a `remove_queries`/`set_queries` method or something like that

**Describe alternatives you've considered**
The only alternative I can see is to make a brand new message then add everything but the query from the original only

**Comment by bluejekyll** [comment]
I think we added this in 0.20, there is an alpha release of that if you want to try it out: `https://docs.rs/trust-dns-proto/0.20.0-alpha.1/trust_dns_proto/op/message/struct.Message.html#method.queries_mut`

Will that meet your needs?

**Comment by leshow** [comment]
Oh, haha, I'm pretty sure I added this actually. I totally forgot I added it for queries! Yes that works.
