### ISSUE TITLE
Upgrade to tokio v0.3

### ISSUE THREAD

**Issue by zonyitoo** [bluejekyll/trust-dns#1250]
Tokio v0.3 have been released: https://tokio.rs/blog/2020-10-tokio-0-3

**Comment by bluejekyll** [comment]
Not clear what work there is here right now.

**Comment by zonyitoo** [comment]
At lease the following works have to be done: :P

1. Upgrade tokio version in Cargo.toml
2. Compatible with the lastest `AsyncRead::poll_read`
3. `runtime::Handle` is no longer public

**Comment by djc** [comment]
For now, this is blocked on new tokio-rustls, tokio-tls and tokio-openssl releases.

**Comment by bluejekyll** [comment]
Handle is no longer public? Hm. I must have missed that in the Tokio dev messages.

I’m a fan of handle specifically to know when a runtime has actually been instantiated in a typesafe way.

**Comment by djc** [comment]
It looks like tokio-tls is no longer being maintained and new development happens in tokio-native-tls (see #1251). It looks like all of tokio-rustls, tokio-native-tls and tokio-openssl now have tokio 0.3-compatible releases.

@bluejekyll can we assume that the next trust-dns release will be tokio 0.3 only?

**Comment by bluejekyll** [comment]
yes. I think so.

**Comment by zonyitoo** [comment]
Hello, what's the status of migrating to tokio v0.3? @bluejekyll

**Comment by bluejekyll** [comment]
#1262 Not looking good right now.

**Comment by LEXUGE** [comment]
> Hello, what's the status of migrating to tokio v0.3? @bluejekyll

If you are on hurry of migrating to tokio v0.3, you could probably adopt [tokio-compat](https://docs.rs/tokio-compat-02/0.1.2/tokio_compat_02/) first. I tested that out and it works fine with trust-dns-resolver.

**Comment by bluejekyll** [comment]
> > Hello, what's the status of migrating to tokio v0.3? @bluejekyll
> 
> If you are on hurry of migrating to tokio v0.3, you could probably adopt [tokio-compat](https://docs.rs/tokio-compat-02/0.1.2/tokio_compat_02/) first. I tested that out and it works fine with trust-dns-resolver.

Would you mind posting an example?

**Comment by LEXUGE** [comment]
> > > Hello, what's the status of migrating to tokio v0.3? @bluejekyll
> > 
> > 
> > If you are on hurry of migrating to tokio v0.3, you could probably adopt [tokio-compat](https://docs.rs/tokio-compat-02/0.1.2/tokio_compat_02/) first. I tested that out and it works fine with trust-dns-resolver.
> 
> Would you mind posting an example?

https://github.com/LEXUGE/dcompass/blob/4da162b756ce11b88ea49ec640cd1e47fc1f282c/dcompass/src/filter.rs#L84

Like above, add `use tokio_compat_02::FutureExt;` and use `.compat()` before `.await` whenever necessary. That helps me to use tokio v0.3 features with trust-dns v0.19.5.

**Comment by MikailBag** [comment]
Let me note that tokio-compat-02 uses single-thread runtime. It means all tasks spawned using tokio 02 APIs will not benefit from multiple CPU cores. Maybe it's the reason of performance problem.
