### ISSUE TITLE
Question / Feature: Shared Trust-DNS and Runtime(tokio/*)

### ISSUE THREAD

**Issue by JRAndreassen** [bluejekyll/trust-dns#1260]
Hi...

I have a couple of questions regarding instantiating Trust-DNS in a app using Tokio...

1) Is there a way to tell Trust-DNS to use the "Current" runtime ?
     Since there is already a Tokio instance running, creating another seems a bit excessive.
     (Perhaps use the current and add a few worker threads to it).
     It would be a great addon to Tokio 0.3.0 [#1250]

2) My application relies on reqwest , which also uses trust-dns...
  Is there a way to share this instance ?
  As it goes, I have 3-tokio runtimes and 2 Trust-DNS instances running

**Comment by bluejekyll** [comment]
To get access to the current Runtime in Tokio, there is this method in 0.2: https://docs.rs/tokio/0.2.22/tokio/runtime/struct.Handle.html#method.current

I believe in tokio 0.3, this method will be the only way, as handle has been removed: https://docs.rs/tokio/0.3.0/tokio/fn.spawn.html

**Comment by bluejekyll** [comment]
To be clear, trust-dns does not yet support Tokio 0.3.

You will need a Runtime associated to the current thread. This can be done in many ways, but the simples is to have a single point where you spawn all the futures.

**Comment by JRAndreassen** [comment]
Hi…

 

Yes, I saw the issue to move it forward to 0.3.0…

I’ll be looking out for it, when it is finished…

 

I did a quick test, using the handle.spawn…

It got stuck somewhere…

I’ll have to chase it later…

 

Thanks for responding…

   JR

**Comment by djc** [comment]
I found this bug report a bit vague on the details. How do you notice that you have 3 tokio runtimes and 2 trust-dns instances running? What do you mean by "instances"? Why is having these instantiated a problem for you?

At least for trust-dns-resolver, it doesn't look like `AsyncResolver` will start its own runtime, so sharing a tokio runtime with other tasks seems fairly straightforward. Can you share some of your application code, or, preferably, a reduced code sample that leads to running 3 tokio runtimes and 2 trust-dns instances?

It does look a little unfortunate that reqwest doesn't give you access to the trust-dns resolver it is using, or a way to configure it, which might be nice, but that would probably require some work on the reqwest side.

**Comment by JRAndreassen** [comment]
@djc : 
  Well, I'm sorry... Did not mean to be "vague"...
Regarding the instances..:
1) #[tokio::main]  Or #[tokio::test(core_threads = 4)]
2) let runtime = tokio::runtime::Runtime::new().expect("failed to launch Runtime");  (See #1259 )
3) from reqwest::connect
```rust
    #[cfg(feature = "trust-dns")]
    pub(crate) fn new_trust_dns() -> crate::Result<HttpConnector> {
        TrustDnsResolver::new()
            .map(hyper::client::HttpConnector::new_with_resolver)
            .map(Self::TrustDns)
            .map_err(crate::error::builder)
    }
}
```

By default, a tokio runtime will create 1 thread per core... Right...
My machine has 16-cores...
The application, running in production mode has 78 threads....
Though I can't give you the definitive proof, without doing a lot of work,
I think it is fairly safe to say, there is at least 3 Tokio runtimes active...
I will however create a sample (modify #1259 ) with a Reqwest client in addition to the sample above...

  JR

**Comment by djc** [comment]
If you have `#[tokio::main]` or `#[tokio::test(core_threads = 4)]`, there's no need to start a runtime explicitly, why are you doing so?

**Comment by JRAndreassen** [comment]
@djc 
Well, I tried to spawn with handle and pass it, but it paniced with a "No runtime"..

I guess the question I should ask is:
  What is the correct way to spawn trust-dns when already running in a tokio context ?

I appreciate the pointer's...
   JR

**Comment by bluejekyll** [comment]
@JRAndreassen, what is it that you want to do? The answer to your question depends a bit on how you plan to use the library.

**Comment by JRAndreassen** [comment]
@bluejekyll ...

It's pretty straight forward and reverse lookups...
I'm using it to time forward resolutions and reverse for display.
So, nothing fancy, just everyday lookups..
I do need to have a "Global" handle since there will be a lot of threads running...
(See #1259 )

I appreciate the assistance.
  JR

**Comment by JRAndreassen** [comment]
I got it to work...
See #1259
