### ISSUE TITLE
NameServerConfig and Protocol serde serialization options

### ISSUE THREAD

**Issue by zonyitoo** [bluejekyll/trust-dns#1282]
**Is your feature request related to a problem? Please describe.**

`NameServerConfig` is now consist of 3 mandatory fields, if we deserialize it from JSON, it will look like:

```json
{
    "socket_addr": "8.8.8.8:53",
    "protocol": "Tcp",
    "trust_nx_responses": false
}
```

It would be a lot nicer that `Tcp` could be represented as `tcp`, and `trust_nx_responses` become an optional field (default `false`.

**Describe the solution you'd like**

For `NameServerConfig`:

```rust
pub struct NameServerConfig {
    // Set default value to this field if it doesn't include in input
    #[cfg_attr(feature = "serde-config", serde(default))]
    pub trust_nx_responses: bool,
}
```

For `Protocol`:

```rust
pub enum Protocol {
    #[cfg_attr(feature = "serde-config", serde(alias = "udp", alias = "UDP"))]
    Udp,

    #[cfg_attr(feature = "serde-config", serde(alias = "tcp", alias = "TCP"))]
    Tcp,

    // ... And so on...
}
```

I could make a PR for this if it is Ok.

**Comment by bluejekyll** [comment]
That sounds great. Feel free.
