### ISSUE TITLE
lru_cache panics during lookup in Rust 1.48

### ISSUE THREAD

**Issue by sudarshan-reddy** [bluejekyll/trust-dns#1302]
**Describe the bug**
Errors when trying to make an insert into the linked hash map. 

**To Reproduce**
Try to call lookup_ip. 

**Expected behavior**

**System:**
 - OS: macOS
 - Architecture:  x86_64
 - rustc version: 1.48.0

**Version:**
Crate: resolver

**Comment by sudarshan-reddy** [comment]
I've attempted to fix this issue here: https://github.com/bluejekyll/trust-dns/pull/1301

**Comment by bluejekyll** [comment]
Can you think of a reason I'm not seeing this error in tests? We have coverage for the minimal use case you describe in the tests.

**Comment by sudarshan-reddy** [comment]
Uh that's strange. I did a diff with the trust_dns I was running to reproduce and the github version: This should be a non issue now since the Cargo.lock holds the fixed version of linked-hash-map: https://github.com/bluejekyll/trust-dns/blob/main/Cargo.lock#L810.

I can close this issue. But do let me know if you still want to consider the hashlink replacement PR.

**Comment by bluejekyll** [comment]
I'm definitely open to updating to better library implementations if there are improvements. I'd like us to consider what reasons we might have for the switch though, right now this feels a little rushed. But If you want to make a case for the PR you've submitted, I'm definitely open.

For some background here, I think we should consider replacing the lru_cache with something simpler and also more configurable. For example, it might be nice to allow folks to swap in a different implementation to say use a file based cache that could be larger than the one in-memory right now.

**Comment by sudarshan-reddy** [comment]
You have some great points here. I initially opened a quick PR because I was worried there could be a break. But in light of the discovery and tests successfully passing Im happy to circle back to a more holistic solution like you describe.
