### ISSUE TITLE
Issue building TRust-DNS 0.10 in Windows

### ISSUE THREAD

**Issue by zsck** [bluejekyll/trust-dns#131]
I've been working today on preparing a build of the software I'm working on for Windows. I've installed OpenSSL according to the description in [the Rust-OpenSSL README](https://github.com/sfackler/rust-openssl#windows-msvc). By the time cargo gets to trying to compile our TRust-DNS 0.10 dependency, however, it encounters a few errors that appear to relate to TRust-DNS' handling of some OpenSSL data.

Below is a screenshot I took of the errors I'm getting.  I'm happy to help out by experimenting with any changes to TRust-DNS in my Windows environment.

![](https://u.nya.is/tbjtzl.png)

Just as a note, one of my colleagues has also experienced the exact same issue separately from me.

**Comment by bluejekyll** [comment]
Are you planning to use TLS with TRust-DNS?

I don't have a windows machine to test against, but the AppVeyor tests for both 32 and 64 but appear to be passing. I didn't set those up myself, but it might be worth looking at the AppVeyor build environment.

If you're not using TLS, the fastest path forward will be to disable the default TLS feature. You can do that when compiling trust-dns by passing the '--no-default-features'. If you're relying on the DNSSec validation, then you'll need to turn OpenSSL back on with '--features=openssl'

You can specify all of this in Cargo.toml like this:

'''
trust-dns = { version = "^0.10", default-features = false, features = ["openssl"] }
'''

**Comment by bluejekyll** [comment]
Also of note. I migrated away from tokio-tls by default, and instead swapped in tokio-openssl in 0.10.1. If you really want tokio-tls which implemented over native-tls, then you'll want to also depend on trust-dns-native-tls after upgrading to 0.10.1.

**Comment by zsck** [comment]
Thanks so much for the quick response!

It looks like upgrading to 0.10.1 actually resolved the issue I had, so I'll go ahead and close this.

Thanks again!

**Comment by bluejekyll** [comment]
Oh, also, I should mention that AppVeyor only started running after 0.10.0 was cut. So the only version that I know works with Windows is 0.10.1.
