### ISSUE TITLE
[Client] Add examples of use to documentation

### ISSUE THREAD

**Issue by SamWhited** [bluejekyll/trust-dns#132]
It is unclear to me from looking at the documentation what the difference between, say, a `Client` and a `ClientHandler` is, or how you'd perform basic operations (eg. querying DNS srv records, or what type is useful if you want to have a function just take "a client").

Having usage examples in the documentation for each type and in the module documentation for client would make getting started with this library much easier. Similar examples should be added for other modules too.

**Comment by bluejekyll** [comment]
Yes. I keep planning to do this. I will add some when I have some time, but will also gladly accept PRs. 

For now please look at tests: https://github.com/bluejekyll/trust-dns/blob/master/server/tests/client_tests.rs

**Comment by bluejekyll** [comment]
From reddit: "I need to send a dns request to check A, AAAA, MX and SOA records of a domain."

**Comment by bluejekyll** [comment]
FYI, please see https://docs.rs/trust-dns and https://docs.rs/trust-dns-resolver for example docs on the libraries.
