### ISSUE TITLE
Support for SVCB/HTTPS record type

### ISSUE THREAD

**Issue by tanyav2** [bluejekyll/trust-dns#1323]
[trust-dns-client](https://docs.rs/trust-dns-client/0.19.6/trust_dns_client/rr/enum.RecordType.html) does not support [SVCB/HTTPS](https://tools.ietf.org/html/draft-ietf-dnsop-svcb-httpssvc-03) record type. This is now supported by [miekg/dns](https://github.com/miekg/dns/pull/1067) which is a popular Go DNS implementation.

Currently, we can use `RecordType::Unknown(65)` to query this record.

I'm happy to submit a PR for this implementation, if this is something that can be supported.

cc @chris-wood @lekensteyn

**Comment by bluejekyll** [comment]
I haven’t looked at the RFC in detail, but please feel free to put up a PR. Notice the way that we have certain record types split across DNSSEC features to reduce dependencies, you may or may not want to have this be optional for similar reasons.

Happy to explain more if this is not obvious in the code. Thanks!

**Comment by bluejekyll** [comment]
@tanyav2 see #1402
