### ISSUE TITLE
Upgrade to tokio v1.0

### ISSUE THREAD

**Issue by zonyitoo** [bluejekyll/trust-dns#1329]
https://tokio.rs/blog/2020-12-tokio-1-0

**Comment by lberrymage** [comment]
I believe this is dependent on `tokio-openssl` cutting a new release since [it updated to tokio 1.0](https://github.com/sfackler/tokio-openssl/pull/24)

**Comment by IceCodeNew** [comment]
> I believe this is dependent on `tokio-openssl` cutting a new release since [it updated to tokio 1.0](https://github.com/sfackler/tokio-openssl/pull/24)

It's done.

**Comment by djc** [comment]
See #1330.
