### ISSUE TITLE
Ability to mutate Edns options

### ISSUE THREAD

**Issue by leshow** [bluejekyll/trust-dns#1362]
**Is your feature request related to a problem? Please describe.**
If you want to remove options from `options` in `Edns` at the moment, you need to create a new `Edns` and not add the options you want to remove.

**Describe the solution you'd like**
We've a modified branch of `trust_dns_proto` already that adds the `remove_option` method to `Edns` and a `remove` method to `OPT`. I believe this would satisfy the above situation. If you're alright with all of this I can submit the branch. `Edns` also provides `options` and arguably we can provide `options_mut` also to make the methods symmetric.

**Describe alternatives you've considered**
As previously stated, the alternative is creating a new `Edns` and copying over everything except the items you wanted to remove.

[options docs](https://docs.rs/trust-dns-proto/0.20.0/trust_dns_proto/op/struct.Edns.html#method.option)

**Comment by djc** [comment]
If you have made changes already, please submit a PR so we can review them directly.
