### ISSUE TITLE
Support `&String` for `IntoName`

### ISSUE THREAD

**Issue by Inrin** [bluejekyll/trust-dns#1411]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Implement `IntoName` Trait for `&'a String`

**Describe alternatives you've considered**
Just use:
1) `as_str()` or `&*foo`
2) Clone the String to not move it.

**Additional context**
https://docs.rs/trust-dns-resolver/0.20.0/trust_dns_resolver/struct.Resolver.html#method.txt_lookup
implies it behaves like a `&str` Parameter.

https://docs.rs/trust-dns-resolver/0.20.0/trust_dns_resolver/struct.AsyncResolver.html#method.txt_lookup
just mentions *a string*

So my first try had been to use: `&foo` where foo is  a `String`.

**Comment by bluejekyll** [comment]
You can use this method: https://doc.rust-lang.org/alloc/string/struct.String.html#method.as_str, though, be aware, `&str` will still allocate for `Name`.

**Comment by Inrin** [comment]
Yes sure!
I used `as_str()` as mentioned in "Describe alternatives you've considered".

This is just a "convenience" feature request ;)

**Comment by bluejekyll** [comment]
yeah, I saw that. I was confused if that was working as expected or not. We can add that conversion if it simplifies things.

**Comment by Inrin** [comment]
Would be nice!
Thank you!

**Comment by bluejekyll** [comment]
Fixed in #1434
