### ISSUE TITLE
bad dns_name: 1.1.1.1

### ISSUE THREAD

**Issue by onoketa** [bluejekyll/trust-dns#1412]
**Describe the bug**
```bad dns_name: 1.1.1.1 ``` when using 1.1.1.1 as ```tls_dns_name``` in ```ResolverConfig```

**To Reproduce**
```rust
let mut resolver = ResolverConfig::new();
				resolver.add_name_server(NameServerConfig {
					//...
					protocol: trust_dns_resolver::config::Protocol::Https,
					tls_dns_name: Some("1.1.1.1".to_string()),
					//...
					//...
				});
```

**Expected behavior**
```https://1.1.1.1/dns-query``` is a valid DoH service so it should not be a bad dns name

**System:**
 - OS: Arch Linux
 - Architecture: x86_64
 - Version 5.10.23
 - rustc version: 1.48.0

**Version:**
Crate: resolver
Version: 0.20

**Comment by djc** [comment]
The rustls stack doesn't support connecting to IP addresses over TLS. You can use the domain name or switch to native-tls via the relevant feature flags.

**Comment by bluejekyll** [comment]
Additionally, I don't believe that is the correct SNI for cloudflare, which I'm nearly certain is `cloudflare-dns.com`. For ease of use you can just use the Cloudflare configs baked in: `ResolverConfig::cloudflare_https`.

**Comment by onoketa** [comment]
> Additionally, I don't believe that is the correct SNI for Cloudflare, which I'm nearly certain is `cloudflare-dns.com`. For ease of use you can just use the Cloudflare configs baked in: `ResolverConfig::cloudflare_https`.

When you connect with 1.1.1.1 there is no SNI in client hello. In China, connecting to 1.1.1.1 with an SNI 'cloudflare-dns.com' is banned by the Great Firewall. It will be helpful if connecting without SNI is supported in trust-dns's DNS over HTTPS resolver.

**Comment by djc** [comment]
As I mentioned, I think this would work with the openssl or native-tls support already available in the resolver crate. You just have to configure it using the crate's Cargo features.

**Comment by onoketa** [comment]
> As I mentioned, I think this would work with the openssl or native-tls support already available in the resolver crate. You just have to configure it using the crate's Cargo features.

DNS over HTTPS resolver has only rustls support.

**Comment by djc** [comment]
Ah, sorry, I missed that. Maybe we could have an `tls_enable_sni` option for `NameServerConfig` (conditional on `rustls` features) to the `https::HttpsClientStreamBuilder` (and probably also the `dns_over_rustls` stream builder) which can propagate the flag into the rustls `ClientConfig`. @bluejekyll what do you think?

**Comment by bluejekyll** [comment]
I think that sounds fine. We can always add OpenSSL/NativeTLS support, though I've been thinking of dropping OpenSSL and leaning more on Rustls/ring in the long run.

Though, I'm forgetting about SNI right now in terms of security in TLS. Does SNI add any security to the protocol, or is it purely for server-side multi-homing?

**Comment by djc** [comment]
I don't think SNI is important for security.

**Comment by trinity-1686a** [comment]
> Does SNI add any security to the protocol

Some would argue that SNI decrease security as it leaks information on the service being reached, creating the need for something like [Encrypted SNI](https://tools.ietf.org/html/draft-ietf-tls-esni-10).

**Comment by mokeyish** [comment]
Is there any solution?

**Comment by mokeyish** [comment]
> The rustls stack doesn't support connecting to IP addresses over TLS. You can use the domain name or switch to native-tls via the relevant feature flags.

When I switch to native-tls, it compiled failure.

<img width="875" alt="image" src="https://user-images.githubusercontent.com/16131917/199208220-7f9fa81a-c1fd-49b1-be35-b0ed08d06936.png">

**Comment by mokeyish** [comment]
> Yes, it looks like DNS over HTTPS is currently only supported with rustls. If you want, consider submitting a PR to add a `dns-over-https-native-tls` feature (which probably wouldn't be very hard, mostly just a bunch of copy and pasting from the `dns-over-https-rustls` code -- though of course we'd prefer to abstract over the difference instead of outright copying where possible).
> 
> (As a rustls co-maintainer, rustls is likely to have support for IP address in certificates by the end of January.)

Thanks， currently, I just log a warning and skip the nameserverconfiggroup. DOH with ip address just used to bootstrap query, using cloudflare-dns is enough.
