### ISSUE TITLE
Replace all min & max constructs with clamp

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#1445]
This is a code cleanup. There are a lot of places in the code where min and max are applied to values to ensure they are between to valid min and max values. In Rust 1.50, clamp was introduced, this would be an improvement: https://doc.rust-lang.org/std/cmp/trait.Ord.html#method.clamp

**Comment by chrismiceli** [comment]
My attempt to resolve this issue is available for review https://github.com/bluejekyll/trust-dns/pull/1473
