### ISSUE TITLE
Update requests to BIND9 fail with FORMERR due to EDNS

### ISSUE THREAD

**Issue by astro** [bluejekyll/trust-dns#1491]
**Describe the bug**
I am using **tdns-cli**'s [tsig implementation](https://github.com/rotty/tdns-cli/blob/master/src/tsig.rs) to send updates to a BIND9 server. If I use **tdns-cli**'s `update_message` module this works. When I use **trust-dns-client** directly, the server replies with `FORMERR`.

**To Reproduce**
* Prepare update requests
* Add TSIG signatures
* Send to BIND9 server

**Expected behavior**
The difference between **tdns-cli** and **trust-dns-client** boils down to this workaround:
```patch
diff --git crates/client/src/op/update_message.rs crates/client/src/op/update_message.rs
index d61794be..5d7a1fcf 100644
--- crates/client/src/op/update_message.rs
+++ crates/client/src/op/update_message.rs
@@ -480,11 +480,11 @@ pub fn delete_rrset(mut record: Record, zone_origin: Name) -> Message {
     message.add_update(record);
 
-    // Extended dns
-    {
-        let edns = message.edns_mut();
-        edns.set_max_payload(MAX_PAYLOAD_LEN);
-        edns.set_version(0);
-    }
 
     message
 }
```

**Following up**
Would it be a good idea to make this configurable? Where/how?

**Comment by bluejekyll** [comment]
Yes. I think we’d want the client to be configurable to disable EDNS. I’d probably start by adding the configuration option to the client, and then following that through to here (which might get messy). I’d have to look at the code in more detail.
