### ISSUE TITLE
Always fall back to other name servers on DNS error response codes

### ISSUE THREAD

**Issue by peterthejohnston** [bluejekyll/trust-dns#1519]
**Is your feature request related to a problem? Please describe.**

As mentioned in this [recently merged PR](https://github.com/bluejekyll/trust-dns/pull/1513), in using trust-dns-resolver as the DNS resolver for [Fuchsia](http://fuchsia.dev/), we have noticed that there are some authoritative DNS name servers that respond with a `REFUSED` response to indicate not a fatal/terminal query error but that the requested domain is not in the list of hosts the server would respond to queries about.

We've also now seen a number of servers responding with a `FORMERR` response (format error, [response code 1](https://datatracker.ietf.org/doc/html/rfc1035#section-4.1.1)) to queries we produce, and it's not clear why.

**Describe the solution you'd like**

We were thinking the best solution here could be to always fall back to trying other name servers on an error response code, and only if queries to all specified DNS servers fail would we return a final query error, to make trust-dns-resolver more resilient to these server responses. @bluejekyll, you [mentioned that](https://github.com/bluejekyll/trust-dns/pull/1513#issuecomment-868180954) trust-dns may want to become more lax than it currently is with fallback/terminal errors.

Would it be feasible to always try the fallback servers on an error response, and only bail with some final error code if all servers have already been tried? I would be happy to put together a PR for this if you think this is reasonable.

**Comment by djc** [comment]
Seems reasonable to me. What policy will you pick for which error to return?

**Comment by peterthejohnston** [comment]
That's a good question. The simplest solution would probably be for the resolver to return the most recent error it received, i.e. from the last name server it tried. Although maybe it would make more sense to get the error returned from the highest priority name server, if the query does terminally fail in the end?

**Comment by bluejekyll** [comment]
Yes. I think the simplest would be to alway try other nameservers. I imagine there are folks who don’t want this (ie want faster responses). There is a flag on the resolver to distrust nameserver responses. Have you played with that setting?

**Comment by djc** [comment]
Yeah, I think returning the error from the first server is probably best.

**Comment by peterthejohnston** [comment]
@bluejekyll do you mean the [`NameServerConfig::trust_nx_responses`](https://docs.rs/trust-dns-resolver/0.20.3/trust_dns_resolver/config/struct.NameServerConfig.html#structfield.trust_nx_responses) flag—whether to trust negative responses from the nameserver? It looks like it defaults to `false` (by default the resolver distrusts `SERVFAIL`, `NXDOMAIN` and NoError/Empty responses), and we haven't overridden that in Fuchsia.

I think that flag does get us the behavior we want for those error types; however, I guess what I'm thinking we want is a more general `trust_error_responses: false` kind of behavior, where we don't trust any response with an error code until we've tried all the nameservers.

@djc sounds good, I can look into how that might be implemented.

**Comment by peterthejohnston** [comment]
> Yeah, I think returning the error from the first server is probably best.

I wanted to clarify something about the implementation of this—I'm still not totally familiar with the code base, but it appears to me that in general, retry behavior in the client comes from the [`RetryDnsHandle`](https://docs.rs/trust-dns-proto/0.20.3/trust_dns_proto/xfer/retry_dns_handle/struct.RetryDnsHandle.html). I was thinking it would make most sense to retain the first error response received in the [`RetrySendStream`](https://github.com/bluejekyll/trust-dns/blob/99c1f03f4a3bf2222261cad6c706b41bb9e2c9d7/crates/proto/src/xfer/retry_dns_handle.rs#L74) (and handle returning it in its implementation of `Stream::poll_next`).

Does that approach make sense? Am I missing anything about how retry behavior occurs?

**Comment by djc** [comment]
Yes, I think that makes sense.
