### ISSUE TITLE
Docs.rs is failing to build trust-dns due to failure in dependency chain with Tokio

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#1535]
**Describe the bug**
Docs.rs is failing to build trust-dns due to failure in dependency chain with Tokio

**To Reproduce**
https://docs.rs/crate/trust-dns-proto/0.21.0-alpha.1/builds/421275

Can be reproduced in the proto crate with `cargo +nightly rustdoc --lib "-Zrustdoc-map" "--all-features" "-Z" "unstable-options" "--config" "build.rustflags=[\"--cfg\", \"docsrs\"]"`, the command that docs.rs appears to use.

**System:**
docs.rs

**Comment by djc** [comment]
I pinged #tokio-dev on Discord.

**Comment by bluejekyll** [comment]
Oh. I already got an answer: 

> It's because Tokio has `any(docsrs, windows)` on the named pipe module. The next release will fix it

https://discord.com/channels/500028886025895936/642133776343760896/874519999719555082

**Comment by bluejekyll** [comment]
The disappointing thing is that I was really excited to see all the feature flag docs in this release!

**Comment by bluejekyll** [comment]
This is resolved: https://github.com/tokio-rs/tokio/pull/4020
