### ISSUE TITLE
named with dns-over-openssl feature does not compile

### ISSUE THREAD

**Issue by msrd0** [bluejekyll/trust-dns#1591]
**To Reproduce**

Run the following command in the `bin` folder:

```bash
cargo check --features dns-over-openssl
```

**Expected behavior**

No errors.

**System:**
 - OS: Linux
 - Architecture: amd64
 - Version Rolling Release
 - rustc version: 1.56 (from ArchLinux repository)

**Version:**
Crate: bin
Version: 0.21.0-alpha.4 (and also current main branch)

**Additional context**

This is the compiler error:

```
    Checking trust-dns-server v0.21.0-alpha.4 (/home/msrd0/git/trust-dns/crates/server)
error[E0061]: this function takes 4 arguments but 3 arguments were supplied
   --> crates/server/src/server/server_future.rs:283:29
    |
283 | ...                   self::handle_raw_request(
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^ expected 4 arguments
284 | ...                       message,
    |                           -------
285 | ...                       handler.clone(),
    |                           ---------------
286 | ...                       stream_handle.clone(),
    |                           --------------------- supplied 3 arguments
    |
note: function defined here
   --> crates/server/src/server/server_future.rs:562:21
    |
562 | pub(crate) async fn handle_raw_request<T: RequestHandler>(
    |                     ^^^^^^^^^^^^^^^^^^
563 |     message: SerialMessage,
    |     ----------------------
564 |     protocol: Protocol,
    |     ------------------
565 |     request_handler: Arc<Mutex<T>>,
    |     ------------------------------
566 |     response_handler: BufDnsStreamHandle,
    |     ------------------------------------

For more information about this error, try `rustc --explain E0061`.
error: could not compile `trust-dns-server` due to previous error
```

**Comment by djc** [comment]
Out of curiosity, is there a particular reason you want to depend on openssl instead of rustls?

**Comment by msrd0** [comment]
Currently, on the alpha version and main branch openssl is a dependency anyways, so I thought I'd give it a try. This can be fixed using resolver 2.

Also, people on discord suggested rustls not supporting certificates issued for ip addresses, but that's no big deal either, as I can use a domain name as well.

**Comment by bluejekyll** [comment]
This is interesting. For some reason we're not running `cargo make dns-over-openssl` in CI. I wonder why that happened.

We've discussed dropping OpenSSL completely in the past. I don't think there's any strong reason to keep it around now.
