### ISSUE TITLE
missing field `tls_config` in initializer of `NameServerConfig`

### ISSUE THREAD

**Issue by williamdes** [bluejekyll/trust-dns#1647]
**Describe the bug**

While building our docker image I was thinking that I could enable all features but it seems like not.
Here is the error I have (reproduced here: https://github.com/trust-dns/docker/runs/5352792304?check_suite_focus=true#step:3:896)

```
   Compiling trust-dns-util v0.21.0 (/workspace/util)
error[E0063]: missing field `tls_config` in initializer of `NameServerConfig`
   --> util/src/resolve.rs:154:27
    |
154 |         name_servers.push(NameServerConfig {
    |                           ^^^^^^^^^^^^^^^^ missing `tls_config`

error[E0063]: missing field `tls_config` in initializer of `NameServerConfig`
   --> util/src/resolve.rs:164:27
    |
164 |         name_servers.push(NameServerConfig {
    |                           ^^^^^^^^^^^^^^^^ missing `tls_config`

```

After removing the feature from the list the build step passes: https://github.com/trust-dns/docker/runs/5352804946?check_suite_focus=true#step:3:891

**To Reproduce**
Clone https://github.com/trust-dns/docker
Edit `alpine/Dockerfile` to add the feature `dns-over-https-rustls` on line 8

**Expected behavior**
Build

**System:**
 - OS:Alpine 3.14
 - rustc version: 1.59

**Version:**
Version: 0.21.0

**Additional context**
Feature: `dns-over-https-rustls`

**Comment by bluejekyll** [comment]
I was able to reproduce your error, I'm trying to figure out why this is happening, it seems like it should work as is, but clearly is not. I'll come up with a fix and publish a 0.21.1 release.

**Comment by bluejekyll** [comment]
@williamdes, 0.21.1 has been published, should fix the issue you were seeing.

**Comment by williamdes** [comment]
Hi @bluejekyll 
Thank you so much for the quick fix and release !
It works: https://github.com/trust-dns/docker/actions/runs/1909071075

I will make a 0.21.1 release in docker when you have some time to fill details for: https://github.com/trust-dns/docker/issues/1 ;)
