### ISSUE TITLE
server panic with message Transport endpoint is not connected

### ISSUE THREAD

**Issue by kontsaki** [bluejekyll/trust-dns#1664]
Hello, i am not sure if this will help and feel free to close this issue if it seems like a waste of your time.

i'm getting this from time to time since a year ago

```
thread 'trust-dns-server-runtime' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }', /home/kon/src/trust-dns/crates/server/src/server/server_future.rs:131:63
```
running on debian bullseye through systemd

i'm not sure how to reproduce this, should i set RUST_BACKTRACE and wait for this to happen again?

**Comment by bluejekyll** [comment]
This is interesting. We should definitely fix this. Clearly an assumption is not true at some points.

**Comment by kontsaki** [comment]
If there is anything I can do to help or provide more information about the system that I'm running, I would be happy to.

**Comment by bluejekyll** [comment]
Actually, one additional piece would be useful, what version of trust-dns are you using?

**Comment by kontsaki** [comment]
I'm pulling and building regularly, at least once a month, from master. Last commit i've checked out was 22ffc3fd2abf88d25a0f70186cb9fdcc2be95702 but i have logs of this happening since 2021-01-18

**Comment by bluejekyll** [comment]
ah, I just took a look. this is a quick and easy fix.
