### ISSUE TITLE
Borrow `Handle`s, don't consume them

### ISSUE THREAD

**Issue by rushmorem** [bluejekyll/trust-dns#167]
I noticed a number of methods (eg `UdpStream::new`) consume `tokio_core::reactor::Handle` instead of simply borrowing it since the underlying methods only require references. This results in unnecessary cloning in client code.

**Comment by bluejekyll** [comment]
Hmm. Did this change in recent Tokio versions?

I think AsRef<Handle> as the parameter change would fix this without creating a breaking change.

**Comment by rushmorem** [comment]
> Did this change in recent Tokio versions?

As long as I remember, this has always been the case. Methods in Tokio have always borrowed `Handle`.

**Comment by bluejekyll** [comment]
Huh. I don't know why I would have made that mistake. I'm on a family vacation right now. I might be able to get to this at some point this week. Otherwise a PR is always welcome.

**Comment by rushmorem** [comment]
> I think AsRef as the parameter change would fix this without creating a breaking change.

IMHO it might actually be desirable to make this a breaking change otherwise people might not be aware of it.

> I'm on a family vacation right now. I might be able to get to this at some point this week. Otherwise a PR is always welcome.

Don't worry about it. Please enjoy your vacation. I will work on this and submit a pull request.

**Comment by bluejekyll** [comment]
> make this a breaking change otherwise people might not be aware of it.

Yeah. I thought about that. It makes sense, I'll plan on a 0.11 release for this in a little bit in that case.

And thanks for the PR!
