### ISSUE TITLE
disallowed_by_std3_ascii_rules problem

### ISSUE THREAD

**Issue by RickSKy** [bluejekyll/trust-dns#1734]
**Describe the bug**
```rust
let mut response = resolver.ipv4_lookup("http://statototalitario.com/stub/index.php").await.unwrap();
    println!("{:#?}", response);
```
the program do not send the query packet, and return err like: 
```bash
 thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ResolveError { kind: Proto(ProtoError { kind: Msg("Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules })") }) }'
```

but on any os platform, we use nslookup:
```bash
nslookup http://statototalitario.com/stub/index.php
Server:		127.0.0.53
Address:	127.0.0.53#53

** server can't find http://statototalitario.com/stub/index.php: NXDOMAIN
```
it send the query packet, and return NXDOMAIN.
why need this unnormal query?  just for some security verify purpose .

**Expected behavior**
send the query packet,and return NXDOMAIN result

**System:**
 - OS:  ALL OS

**Version:**
Crate: trust-dns-proto
Version: 0.21

**Comment by bluejekyll** [comment]
I'm not sure I understand what you're attempting to do here. The lookup methods expect a domain name as the input, but a full URL. For example instead of `http://statototalitario.com/stub/index.php` you'd want to pass in `statototalitario.com`.

To extract this information, you could use this method from the `url` crate to get the domain: https://docs.rs/url/2.2.2/url/struct.Url.html#method.domain

**Comment by RickSKy** [comment]
wireshark or tcpdump capture the dns query packet, you will see below 
```
Name: http://statototalitario.com/stub/index.php
 Name Length:42
 Label Count:3
Type: A (Host Address) (1)
 Class:IN (0x0001)

```

**Comment by bluejekyll** [comment]
If you want to construct an invalid Name and send it, you can use the from labels methods https://docs.rs/trust-dns-proto/0.21.2/trust_dns_proto/rr/domain/struct.Name.html#method.from_labels and construct the labels using from raw bytes https://docs.rs/trust-dns-proto/0.21.2/trust_dns_proto/rr/domain/struct.Label.html#method.from_raw_bytes

**Comment by RickSKy** [comment]
Thanks.

**Comment by delta4chat** [comment]
The error still occurs for resolving domain `foo_bar.com`, so sometimes this causes actual problems, such as when querying the SPF of some domain: `dig spf_a0.gsa.gov -t TXT @127.0.0.1 -p 1053`

In other resolvers (such as 8.8.8.8) query this should returns some TXT record with IP ranges.

```
dig spf_a0.gsa.gov -t TXT @8.8.8.8
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 51685
;; Flags: qr rd ra; QUERY: 1; ANSWER: 1; AUTHORITY: 0; ADDITIONAL: 0

;; QUESTION SECTION:
;; spf_a0.gsa.gov.              IN      TXT

;; ANSWER SECTION:
spf_a0.gsa.gov.         10800   IN      TXT     "v=spf1 ip4:159.142.1.236 ip4:159.142.38.196/30 ip4:159.142.160.13 ip4:159.142.166.247 ip4:159.142.1.214/31 ip4:159.142.1.216 ip4:159.142.1.218/31 ip4:159.142.72.63/30 ip4:159.142.72.68 ip4:159.142.191.80 ip4:159.142.134.75 ~all"

;; Received 272 B
```

**Comment by delta4chat** [comment]
Is there any way or option to bypass this error so that DNS query packets containing underscores can be correctly parsed?
