### ISSUE TITLE
Make maximum request depth configurable for DNSSEC validating requests

### ISSUE THREAD

**Issue by wiktor-k** [bluejekyll/trust-dns#1735]
**Is your feature request related to a problem? Please describe.**

When DNSSEC validation is enabled lookup of OPENPGPKEYs fails with "max validation depth reached" error for some addresses e.g. `A47CB586A51ACB93ACB9EF806F35F29131548E59E2FACD58CF6232E3._openpgpkey.debian.org`.

The current hardcoded limit is 20. The validation succeeds when the limit is adjusted to be 22.

**Describe the solution you'd like**

I'd like to have configurable max validation depth. This solution has already been hinted in the code, see: https://github.com/bluejekyll/trust-dns/blob/main/crates/proto/src/xfer/dnssec_dns_handle.rs#L119

**Describe alternatives you've considered**

Adjusting the hardcoded limit to 22 that is not significantly bigger than the current 20. The downside is that I may have to adjust it in the future.

**Additional context**

I've actually taken some time and made a commit that makes max depth configurable in DnsRequestOptions: https://github.com/wiktor-k/trust-dns/commit/b42061cfd2caa707ac3dbd097ec31607892e0d58

And the code that I'm using with that commit in (slightly tweaked):

```rust
    let fqdn = "A47CB586A51ACB93ACB9EF806F35F29131548E59E2FACD58CF6232E3._openpgpkey.debian.org";

    let mut opts = ResolverOpts::default();
    opts.validate = true;

    let resolver = TokioAsyncResolver::tokio(Default::default(), opts)?;

    let mut request_options = DnsRequestOptions::default();
    request_options.max_request_depth = 40; // <-- set depth

    let answers = resolver
        .lookup(fqdn, RecordType::OPENPGPKEY, request_options)
        .await?;

    for record in answers.iter() {
        if let RData::OPENPGPKEY(key) = record {
            eprintln!("{:?}", key.public_key());
        }
    }
```

I'm using the following features:

```toml
trust-dns-client = { version = "0.21.2" }
trust-dns-resolver = { version = "0.21.2", features = ["dnssec-ring"] }
trust-dns-proto = { version = "0.21.2", features = ["dnssec-ring"] }
```

Unfortunately it seems that while the first request has the max request depth I'd like the DNSSEC validation creates additional requests that use the default value (20). This can be seen by using the following commit: https://github.com/wiktor-k/trust-dns/commit/cbbdb57f1b8f37b8cb0d56f98a32d87d891c5c77

```
$ cargo run -- dane get dkg@debian.org
   Compiling trust-dns-proto v0.21.2 (/home/wiktor/src/pep/trust-dns/crates/proto)
   Compiling trust-dns-resolver v0.21.2 (/home/wiktor/src/pep/trust-dns/crates/resolver)
   Compiling trust-dns-client v0.21.2 (/home/wiktor/src/pep/trust-dns/crates/client)
   Compiling sequoia-net v0.24.0 (/home/wiktor/src/pep/sequoia/net)
   Compiling sequoia-sq v0.26.0 (/home/wiktor/src/pep/sequoia/sq)
    Finished dev [unoptimized + debuginfo] target(s) in 14.21s
     Running `/home/wiktor/src/pep/sequoia/target/debug/sq dane get 'dkg@debian.org'`
MAX: 0 of 40 // <-- my value 40
MAX: 4 of 20 // <-- next request is using default value
MAX: 6 of 20
MAX: 10 of 20
MAX: 12 of 20
MAX: 16 of 20
MAX: 18 of 20
MAX: 22 of 20
```

(Also, why the increments are by 2 or 4? Not sure if that's a tiny issue or just that I'm "holding it wrong" :) )

Since I'm not super-familiar with trust-dns codebase (except for being a happy client) I'd like to ask for Your guidance to how to approach this problem.

Thanks in advance! :wave:

**Comment by bluejekyll** [comment]
Thanks for the PR. I think the values I picked here were chosen somewhat arbitrarily. I'm fine with us raising this.

In terms of the way the counter is being used, it's possibly that we're seeing the counter jump by two because of parallel requests (which defaults to 2). In terms of why your value isn't carrying through, I'm guessing that somewhere the `DnsRequestOptions` is being reset to default and not passed through properly. That is, there's probably a bug where a default one is being created and not properly passing through the requested one.

**Comment by wiktor-k** [comment]
Thanks for the response @bluejekyll!

How about we approach this issue two-fold: first, increasing the value slightly (e.g. from 20 to 25) so that I can directly use trust-dns for OPENPGPKEY discovery in the wild.

Then, I'd like to dig in the code and see where the default gets reset and fix that (as part of introducing configurable "max validation depth"). This may take some time since I'm not familiar with the codebase but still - I'd like to solve this issue properly :)
