### ISSUE TITLE
MessageResponseBuilder::from_message_request compression is incorrect

### ISSUE THREAD

**Issue by jeff-hiner** [bluejekyll/trust-dns#1743]
**Describe the bug**
When constructing a Response packet via MessageResponseBuilder, the emitted repr is larger than it should be. This happens because the compression dictionary is not initialized with the NAME contents of the already-rendered query, so subsequent serialization of matching Answer RRs is not able to properly compress them. This matters significantly when building responses to things like SRV requests that tend to contain long names, where a full response can easily exceed 512 bytes if compression isn't used.

**To Reproduce**
Given a Request received via `dig @127.0.0.1 -p 5353 google.com.`, manually populate `answers` in the code below with 
an A record for google.com. -> 142.251.214.142, and use the builder to emit a packet.
```
let mut response_headers = Header::response_from_request(request.header());

response_headers.set_recursion_available(true);

let mut response_builder = MessageResponseBuilder::from_message_request(request).build(
    response_headers,
    answers,
    [],
    [],
    [],
);
```
Import the packet into a tool (I used wireshark) to examine it. The NAME "google.com." in Answers is repeated instead of being a relative link to the NAME in the original query.

**Expected behavior**
The first Answer with a NAME matching the query should emit a reference instead of duplicating the canonical name.

**System:**
 - OS: Linux
 - Architecture: x86_64
 - rustc version: 1.62.1

**Version:**
Crate: server
Version: `main`

**Comment by bluejekyll** [comment]
I think this is due to the way we output the request query directly from the original data. Your analysis looks to be correct.
