### ISSUE TITLE
Allow access to lookup's record slice

### ISSUE THREAD

**Issue by izissise** [bluejekyll/trust-dns#1745]
**Is your feature request related to a problem? Please describe.**
I'd like to choose to randomly choose an ip when the response for a domain contains multiple answers,
right now the only way is to `.iter().collect()` on [Lookup](https://docs.rs/trust-dns-resolver/0.21.2/trust_dns_resolver/lookup/struct.Lookup.html#) 

**Describe the solution you'd like**
`Lookup` already have a [records](https://docs.rs/trust-dns-resolver/0.21.2/src/trust_dns_resolver/lookup.rs.html#103) methods, but it exist only for testing, it would be nice if it was available to use.

**Comment by djc** [comment]
I think it might make sense to just expose `records()`. Would you be able to contribute a PR for this?

**Comment by bluejekyll** [comment]
Resolved in #1746
