### ISSUE TITLE
CAA records are Display-ed incorrectly

### ISSUE THREAD

**Issue by wuerges** [bluejekyll/trust-dns#1795]
**Describe the bug**

CAA records are not `Display`-ed as expected:
- A `true` flag is shown as `1` instead of `128`.
- Values other than `true` and `false` are not representable.
- `;` separator is not added in some cases.
- Unknown record is not being displayed as text when/if it could. 

**To Reproduce**

Please consider this PR to explain/fix the issue:
https://github.com/bluejekyll/trust-dns/pull/1794

**Comment by darnuria** [comment]
Your PR allowed to see that [RFC8659](https://www.rfc-editor.org/rfc/rfc8659) render obsolete [RFC6844](https://www.rfc-editor.org/rfc/rfc6844) I think it will take some time to understand the changes but I am not a maintainer.

**Comment by bluejekyll** [comment]
I think this is resolve in #1798, closing. Please reopen if you think there are still open issues.
