### ISSUE TITLE
Memory leak in inner_join / JoinSet

### ISSUE THREAD

**Issue by gopa-eg** [bluejekyll/trust-dns#1809]
https://github.com/bluejekyll/trust-dns/blob/main/crates/server/src/server/server_future.rs#L95

join_next() is never called on inner_join - hence the inner_join will keep growing per dns-request

**Comment by bluejekyll** [comment]
@jeff-hiner any chance you could look at this? I think it’s related to some of your changes. Could you verify if it’s an issue?

**Comment by jeff-hiner** [comment]
Yeah we need to eventually clean these up. I'd normally suggest doing a lazy `try_join_next` right after that spawn, but that doesn't exist. Maybe a `now_or_never` wrapper around `join_next`, in a loop?
