### ISSUE TITLE
resolver `lookup_ip` should checkout `/etc/hosts/` before  dns requests?

### ISSUE THREAD

**Issue by cssivision** [bluejekyll/trust-dns#190]

**Comment by bluejekyll** [comment]
Yeah, hm. The library currently doesn't have any support for `/etc/hosts`. I can see how this would be a valuable request though.

**Comment by cssivision** [comment]
I think this is a most common feature.

**Comment by cssivision** [comment]
i think i can spend some time on this feature.

**Comment by bluejekyll** [comment]
That would be cool! I can help see where is best to put it...

Off the top of my head, I think there should be a new config param, probably a map of all the Names->IPs: https://github.com/bluejekyll/trust-dns/blob/master/resolver/src/lookup_ip.rs#L156 

and then possibly introduce a function or logic here, to lookup from that map: https://github.com/bluejekyll/trust-dns/blob/master/resolver/src/lookup_ip.rs#L156

It will be interesting to see how to thread that through...

**Comment by briansmith** [comment]
This was fixed by #191 and should be closed, AFAICT. I filed follow-ups #251 and #252.
