### ISSUE TITLE
Configuring trust-dns behind Traefik as a DOH server?

### ISSUE THREAD

**Issue by Gontier-Julien** [bluejekyll/trust-dns#1925]
What is the question?

I wanted to know if it would be possible to have trust-dns as a DOH server behind Traefik? ^^
If so could you help me to have an example config file to have it working behind Traefik ^^?

**Comment by djc** [comment]
It's probably possible. I don't think it's likely that the trust-dns maintainers will write a specific example for your use case, but if you write up some things you've tried which haven't worked as expected we might be able to point you in the right direction.

**Comment by Gontier-Julien** [comment]
I don't really know where to start to use trust-dns tho

**Comment by bluejekyll** [comment]
This should be possible. The current best example for DoH is here: https://github.com/bluejekyll/trust-dns/blob/main/tests/test-data/test_configs/dns_over_https.toml

You'd want to combine that with a more complete configuration like this: https://github.com/bluejekyll/trust-dns/blob/main/tests/test-data/test_configs/example.toml

**Comment by Gontier-Julien** [comment]
> This should be possible. The current best example for DoH is here: https://github.com/bluejekyll/trust-dns/blob/main/tests/test-data/test_configs/dns_over_https.toml
> 
> You'd want to combine that with a more complete configuration like this: https://github.com/bluejekyll/trust-dns/blob/main/tests/test-data/test_configs/example.toml

Thank! I'll try that ^^
Also it is possible without using any cert? Since it would be handled by Traefik

**Comment by bluejekyll** [comment]
DoH is designed to run over HTTPS only, so it's not an option to run without a cert. Can you self-sign and register the public key with Traefik? I'm not familiar with that service.

**Comment by Gontier-Julien** [comment]
Alright, well i can tell treafik to not encrypt the traffic and let trust-dns to do it with the cert from traefik that no problem!
Thank for the info tho!

**Comment by Gontier-Julien** [comment]
So as i have some time to finally try this, i have a suggestion, it would be great to have this project support acme.json ^^

**Comment by Gontier-Julien** [comment]
Also i've been struggling to get pass this point:

`thread 'main' panicked at 'could not register TLS listener: Custom { kind: Other, error: "error creating TLS acceptor: unexpected error: invalid private key" }', bin/src/named.rs:617:14`

i've been using this to get the necessary cert and key:

https://github.com/ldez/traefik-certs-dumper

**Comment by Gontier-Julien** [comment]
The current config

```
listen_addrs_ipv4 = ["0.0.0.0"]

## listen_port: port on which to list, default 53
listen_port = 8053

tls_cert = { path = "/ssl-certs/certs/certs/domain.cert.pem", endpoint_name = "domain", cert_type = "pem", private_key = "/ssl-certs/certs/private/domain.key" }

## if true, looks to see if a chained pem file exists at $file.pem (see
## supported_algorithms below).
## these keys will also be registered as authorities for update,
## meaning that SIG(0) updates can be established by initially using these
## keys. the zone will be signed with all specified keys, it may be desirable
## to limit this set for performance reasons.
enable_dnssec = false

[[zones]]
## zone: this is the ORIGIN of the zone, aka the base name, '.' is implied on the end
##  specifying something other than '.' here, will restrict this forwarder to only queries
##  where the search name is a subzone of the name, e.g. if zone is "example.com.", then
##  queries for "www.example.com" or "example.com" would be forwarded.
zone = "."

## zone_type: Primary, Secondary, Hint, Forward
zone_type = "Forward"

## remember the port, defaults: 53 for Udp & Tcp, 853 for Tls and 443 for Https.
##   Tls and/or Https require features dns-over-tls and/or dns-over-https
stores = { type = "forward", name_servers = [{ socket_addr = "8.8.8.8:53", protocol = "udp", trust_nx_responses = false },
                                             { socket_addr = "8.8.8.8:53", protocol = "tcp", trust_nx_responses = false }] }
```

**Comment by Gontier-Julien** [comment]
I'm also just trying to have a DOH server and not a DOT one.

But in the log it keep trying to have a DOT one:

`1687631578:INFO:named:593:loading cert for DNS over TLS: "/ssl-certs/certs/certs/domain.cert.pem"`

**Comment by Gontier-Julien** [comment]
Quick question too since i'm at it haha, is there a fallback system? Or does it already just pick the next forwarder if the first one fail like a fallback ?

**Comment by Gontier-Julien** [comment]
Any news on the situation?

**Comment by Gontier-Julien** [comment]
Could you help me on this situation? I don't really what am i missing here

**Comment by djc** [comment]
Sorry, I don't really have time to provide support for this.
