### ISSUE TITLE
Question: Mutex around AsyncClient

### ISSUE THREAD

**Issue by andrewbaxter** [bluejekyll/trust-dns#1933]
`AsyncClient::query` takes a mutable self.  Since `AsyncClient` will probably be used across threads, I'd expect it to be immutable.  AFAICT wrapping in `Mutex` works fine, but it means you can't do `client.lock().unwrap().query().await` since the guard stays around until the query completes (you need to store `client.lock().unwrap().query()` in one statement then await it in the next).

Should I be doing something else here?

For background, I'm writing the classic "DNS server that handles some requests locally and forwards the rest to 1.1.1.1".

**Comment by djc** [comment]
You probably want to use a resolver rather than a client? [`AsyncResolver::lookup()`](https://docs.rs/trust-dns-resolver/latest/trust_dns_resolver/struct.AsyncResolver.html#method.lookup) takes `&self`.

**Comment by andrewbaxter** [comment]
It seemed like it would be easier to map the parameters and return values from the values the `AsyncClient` uses to that of the `RequestHandler` if I'm just forwarding.  The simplified interface doesn't take a lot of the request information and doesn't include a lot of the response information (authority, additional records, etc).

I'm doing
```
FutureServer -> MyHandler -> AsyncClient
```
maybe that architecture is mistaken.

**Comment by andrewbaxter** [comment]
Okay cool, yeah.  I haven't gotten very far but I'll come back to this once I've gotten my own code more stable.

Would it make more sense to provide an additional alternative query method in resolver that takes the same arguments as Client does for it's query (like `full_lookup` or `raw_lookup` or `advanced_lookup` or something)?

I'm wondering if I shouldn't use resolver instead anyways for the things like using multiple servers, etc.  I'm not sure if resolver has a simple interface just for user friendliness or out of necessity due to abstraction over multiple disparate backends.

**Comment by djc** [comment]
Probably more for the simple interface, but you'll probably only find out for sure if you try! I think some kind of `full_lookup()` (naming to be bikeshedded) probably makes sense.

**Comment by ibigbug** [comment]
I'm also facing the issue, made a PR here https://github.com/bluejekyll/trust-dns/pull/2018

**Comment by andrewbaxter** [comment]
I think this is done in #2018 - I haven't checked but I'll close for now.
