### ISSUE TITLE
The rustls version number is wrong in the 0.23.0-alpha.2 release.

### ISSUE THREAD

**Issue by mokeyish** [bluejekyll/trust-dns#1937]
**Describe the bug**
I don't known why the rustls version number is wrong on the https://crates.io/crates/trust-dns-resolver/0.23.0-alpha.2/dependencies

https://github.com/bluejekyll/trust-dns/blob/41b6e33c51e99db50d873d165d52d70e38f33a34/Cargo.toml#L64

![图片](https://github.com/bluejekyll/trust-dns/assets/16131917/061de4eb-d80b-45fd-9e2c-20b3dd7868d8)

**Expected behavior**

**Version:**
Crate: trust-dns-resolver
Version: 0.23.0-alpha.2

**Comment by djc** [comment]
The alpha [was published](https://github.com/bluejekyll/trust-dns/issues/1922#issuecomment-1546180958) before the update PR was [merged](https://github.com/bluejekyll/trust-dns/pull/1916#event-9247774281), so that seems expected.
