### ISSUE TITLE
DNS over HTTP/3 (DoH3)

### ISSUE THREAD

**Issue by daxpedda** [bluejekyll/trust-dns#1939]
I couldn't find an RFC for this, but [RFC9250](https://datatracker.ietf.org/doc/html/rfc9250/#section-1-11) (DoQ) mentions:
> DNS over HTTPS (DoH) [[RFC8484](https://datatracker.ietf.org/doc/html/rfc8484)] can be used with HTTP/3 to get some of the benefits of QUIC.

This would probably use the [`h3`](https://crates.io/crates/h3) crate.

**Comment by bluejekyll** [comment]
Is the reasoning on this one based on the port usage? I think this should be possible. I haven't reviewed the h3 crate, so I don't know how hard/easy it would be to enable this.
