### ISSUE TITLE
`dns-over-quic` pulls in `rustls-native-certs` by default

### ISSUE THREAD

**Issue by daxpedda** [bluejekyll/trust-dns#1940]
I'm not entirely sure, but it seems to me that `dns-over-quic` uses `webpki` by default:
https://github.com/bluejekyll/trust-dns/blob/41b6e33c51e99db50d873d165d52d70e38f33a34/crates/proto/src/quic/quic_client_stream.rs#L275-L282

But because the `quinn` dependency is used with `default-features`, it pulls in `rustls-native-certs`.

Would a PR be acceptable that changes `quinn` to use `default-features = false`?

**Comment by djc** [comment]
Yeah... although maybe it makes more sense to switch trust-dns to use native-certs everywhere by default?

**Comment by daxpedda** [comment]
> Yeah... although maybe it makes more sense to switch trust-dns to use native-certs everywhere by default?

If you like I could tackle that as well, but I would like to keep the ability to drop the `rustls-native-certs` dependency when not needed.

So one suggestion would be to just introduce a bunch of new features:
- `dns-over-rustls-native-certs`
- `dns-over-rustls-webpki`
- `dns-over-https-rustls-native-certs`
- `dns-over-https-rustls-webpki`
- `dns-over-quic-native-certs`
- `dns-over-quic-webpki`

Or alternatively having to select between the two separately, but having no default at all:
- Leave the old ones:
  - `dns-over-rustls`
  - `dns-over-https-rustls`
  - `dns-over-quic`
- Introduce two new features:
  - `native-certs`
  - `webpki`
