### ISSUE TITLE
Is there a problem with readme example ?

### ISSUE THREAD

**Issue by biswanaths** [bluejekyll/trust-dns#1950]
Regarding https://github.com/bluejekyll/trust-dns/tree/main/crates/client#example

The following code snippet seems to erroring out with compiler asking for type hint. 

`let address = "8.8.8.8:53".parse().unwrap();
`

Is the code snippet wrong or I am doing some thing wrong when trying out the example ?

**Comment by djc** [comment]
This question is hard to answer without the actual error you got from the compiler.

(Did you read the compiler error and try to follow its direction?)

**Comment by biswanaths** [comment]
Sorry for the troubling. 
Only was trying to parse without the using the parsed address, compiler could not get type inference. 

Thank you for the offer of help. And sorry for the trouble.
