### ISSUE TITLE
Resolution fails for a subdomain but not for the root domain

### ISSUE THREAD

**Issue by thosmos** [bluejekyll/trust-dns#1965]
We're attempting to use trust-dns as a local DNS server for an IPv4 NAT network of about 150 OpenWRT routers to reduce the impact on public DNS servers.  So far it's working for the most part, but it's failing on some subdomains like `downloads.openwrt.org` that work when querying via other DNS servers.  I'm wondering if this is a bug or a configuration problem.  `172.168.0.254` is the internal gateway IP where trust-dns is running.

```
% resolve openwrt.org -n 172.168.0.254:53 
Querying for openwrt.org A from tcp:172.168.0.254:53, udp:172.168.0.254:53
Success for query openwrt.org IN A
	openwrt.org. 2512 IN A 139.59.209.225

% resolve downloads.openwrt.org -n 172.168.0.254:53
Querying for downloads.openwrt.org A from tcp:172.168.0.254:53, udp:172.168.0.254:53
Error: ResolveError { kind: NoRecordsFound { query: Query { name: Name("downloads.openwrt.org."), query_type: A, query_class: IN }, soa: None, negative_ttl: None, response_code: NoError, trusted: true } }

% resolve downloads.openwrt.org -n 1.0.0.1:53
Querying for downloads.openwrt.org A from tcp:1.0.0.1:53, udp:1.0.0.1:53
Success for query downloads.openwrt.org IN A
	downloads.openwrt.org. 2367 IN CNAME mirror-02.infra.openwrt.org.
	mirror-02.infra.openwrt.org. 1316 IN A 168.119.138.211	
```

**Comment by bluejekyll** [comment]
Have you enabled debug logging on the `trust-dns` server? Do those show any indication on why it might not be getting a proper response?

The `resolve` command is essentially the same logic as what the server is using with the `Forwarder` configuration. Are you using that setting or the `Recursor` (recursive resolution isn't well tested and considered experimental right now)?

**Comment by thosmos** [comment]
Well this is strange, the debug logs show some resolutions happening, but not the ones I'm attempting, whether they fail or succeed.  Yes the config is set to the `recursor` setting.  I tried changing it to `forward` but got an error about missing a `name_servers` field.  Where are the docs for these config options?

**Comment by bluejekyll** [comment]
oh, it's good to hear that the `recursor` kinda works. I'll use your example to try and workout what's going on with that.

For the forwarding option, we don't have a lot of docs, apologies, here's the best example that I have: https://github.com/bluejekyll/trust-dns/blob/a614257fb0b57471c0903d0c88e15528a69faac5/tests/test-data/test_configs/example_forwarder.toml

**Comment by thosmos** [comment]
That worked and we're now getting reliable resolutions from downstream routers.  Thanks for your work on this!
