### ISSUE TITLE
Graceful shutdown of ServerFuture

### ISSUE THREAD

**Issue by nmittler** [bluejekyll/trust-dns#1976]
**Is your feature request related to a problem? Please describe.**
When running a DNS server (via `ServerFuture`) as part of a larger application, it's desirable to include the shutdown of the DNS server as part of the shutdown workflow for the process.

**Describe the solution you'd like**
Ideally, the DNS server would support hooks to initiate a graceful shutdown, as well as notifying the application when the server shutdown has completed. During a graceful shutdown, the server would finish serving existing requests, but reject new requests.

**Describe alternatives you've considered**
NA

**Additional context**
This came up in an Istio PR, which adds a Trust-DNS-based proxy: https://github.com/istio/ztunnel/pull/536#discussion_r1238781334

**Comment by djc** [comment]
Sounds good to me to add something like this. Maybe look at how hyper models [`Server::with_graceful_shutdown()`](https://docs.rs/hyper/latest/hyper/server/struct.Server.html#method.with_graceful_shutdown)?

**Comment by nmittler** [comment]
Sounds good, I'll take a look. I've already started some hacking using the [linkerd drain](https://github.com/linkerd/drain-rs) crate, since that's what Istio is using currently. I'll compare and see what works best for `ServerFuture`.

**Comment by blaine** [comment]
This is extremely apropos for us! Will be watching this, let us know if we can help. cc @zeeshanlakhani

**Comment by nmittler** [comment]
@blaine @zeeshanlakhani FYI #1977 is out for review if you're interested
