### ISSUE TITLE
`Malformed label: --` when parsing resolv.conf

### ISSUE THREAD

**Issue by Jake-Shadle** [bluejekyll/trust-dns#1985]
**Describe the bug**
My local `/etc/resolv.conf` triggers [this error](https://github.com/bluejekyll/trust-dns/blob/c4e92cf837b2cd5bd5c3567bc405d01cf6eb1f03/crates/proto/src/rr/domain/label.rs#L96), due to the presence of the line `search -- lan`.

**To Reproduce**
Attemp to parse this file:

```txt
nameserver 127.0.0.53
options edns0 trust-ad
search -- lan
```

**Expected behavior**
I would expect this file to be parsed, _if_ it is actually valid, which I'm _assuming_ it is since my system works, but I honestly have no clue if trust-dns or systemd is in the wrong here since my efforts to figure out what the valid form(s) of the search entry in the resolv.conf is/are was met with defeat.

After playing around with my `/etc/systemd/resolved.conf` I'm becoming more convinced that this is a systemd bug, as doing any changes to the `Domains=` field (which controls the search field in resolv.conf) will always result in `--` being appended or prepended to whatever entries I make.

**System:**
 - OS: linux
 - Architecture: x86_64
 - Version: 6.3.8-200.fc38.x86_64
 - rustc version: 1.70.0

**Version:**
Crate: proto
Version: 0.22.0

**Additional context**
I didn't configure this myself and since I've never had this issue in the past, I'm assuming a recent system update added/changed the `search -- lan` entry in the resolv.conf, so I'm assuming other people will start hitting this issue if this is a general update to Fedora 38/systemd-resolv, but that's just a guess.

That being said, I'm not certain this is a bug in trust-dns, but more likely systemd, but figured I would open this issue just in case that is not the case, or at least have a record of this issue if others hit it, as I was unable to find much info elsewhere about this.

**Comment by Jake-Shadle** [comment]
Oh and as a workaround, one can just edit `/etc/resolv.conf` to remove the `--` from the search field, just be aware that those changes will be overwritten if you re/start the `systemd-resolved` service or reboot.

**Comment by Jake-Shadle** [comment]
Took a look at my laptop running PopOS instead of Fedora, but still using systemd, and sure enough the resolv.conf just has `search lan` with no `--`.

**Comment by CodeDead** [comment]
Still, the double dashes are valid config options for /etc/resolv.conf . This bug also impacts the MongoDB Rust driver on Linux.

**Comment by Jake-Shadle** [comment]
Do you have a reference for it in a spec? I tried and failed to find what - - even means.

**Comment by CodeDead** [comment]
https://man.archlinux.org/man/resolv.conf.5#search

**Comment by bluejekyll** [comment]
I have no idea what `—` would mean in this context?

I think one option would be for us to change the resolve.conf parsing to be lossy and ignore illegal input? My guess is this is some awkward default based on other configurations in the system, like no hostname?

**Comment by djc** [comment]
@CodeDead how do you conclude that from those docs? I didn't see anything relevant in that man page?

Maybe we should look at the code (presumably in libc implementations) that parses `resolv.conf`?
