### ISSUE TITLE
DoQ default configuration is invalid

### ISSUE THREAD

**Issue by daxpedda** [bluejekyll/trust-dns#1990]
Currently DoT, DoH and DoQ share the same `ClientConfig`:
https://github.com/bluejekyll/trust-dns/blob/bf04bc8d3efec41d29cf558416b3dbed2d26ae02/crates/resolver/src/tls/dns_over_rustls.rs#L30-L56

All three implementations can't share the same configuration as they differ on some properties:
- **ALPN** (mandatory)
  - DoT: None
  - DoH: "h2" (current)
  - DoQ: "doq"
- **SNI** (optional)
  We probably want to continue disable SNI for DoT by default (though the only public server that I found supporting DoQ, AdGuard, requires SNI for both DoQ and DoT), but disabling SNI for DoH by default is strange.

The fast fix is probably easy, just use a different `ClientConfig` for each protocol. This does have a big downside though, when using multiple backends this will parse the root certificates multiple times.

This in turn could be solved by using [`WebPkiVerifier`](https://docs.rs/rustls/0.21.5/rustls/client/struct.WebPkiVerifier.html), but that would require `dangerous_configuration` and I'm not sure if we want to use that because it would activate it for upstream users as well.

So unless we are fine with activating `dangerous_configuration`, this would probably require some fix in Rustls. Considering @djc maintains both, I'm gonna hold back from creating an issue there until further feedback.

**Comment by djc** [comment]
I think the rustls QUIC code does the right thing here, and will restrict to 1.3 when starting a QUIC connection. Do you have actual evidence to the contrary?

**Comment by daxpedda** [comment]
> I think the rustls QUIC code does the right thing here, and will restrict to 1.3 when starting a QUIC connection. Do you have actual evidence to the contrary?

No! I only tested ALPN and SNI.
I didn't know that, but it makes sense.

**Comment by djc** [comment]
> This in turn could be solved by using [`WebPkiVerifier`](https://docs.rs/rustls/0.21.5/rustls/client/struct.WebPkiVerifier.html), but that would require `dangerous_configuration` and I'm not sure if we want to use that because it would activate it for upstream users as well.

I think rustls would definitely accept a change to take an `Arc<RootCertStore>` instead of `RootCertStore` directly. See also https://github.com/rustls/rustls/issues/1403. Perhaps there's a way of doing this that is semver-compatible? I was thinking `with_root_certificates()` could take some kind of `impl AsRef<RootCertStore> + 'static` but wrangling that in there semver-compatibly might not be feasible.

**Comment by bluejekyll** [comment]
With #2005 merged, what are the potential other changes needed here? Or is that enough?

**Comment by daxpedda** [comment]
#2005 did not fix this issue.

The current plan is to store the root certificates in an `Arc<RootCertStore>` and then store the default `RustConfig` in the runtime. There we need to split it up into a separate `RustConfig` for each backend: DoT, DoH, DoQ.

I'm planning to put up a PR in the next couple of days!

**Comment by bluejekyll** [comment]
Awesome! Thank you!
