### ISSUE TITLE
How to run async dynamic update with DNS SEC?

### ISSUE THREAD

**Issue by dainslef** [bluejekyll/trust-dns#2022]
I know using `SyncClient::with_signer()` can create a sync client to execute DNS SEC dynamic update, but it seems `AsyncClient` has no function to do the same things.

How can I use DNS SEC dynamic update with `AsyncClient`?

Thank you.

**Comment by bluejekyll** [comment]
This isn't the most elegant interface, we should clean it up at some point, but what you want is this method: https://docs.rs/trust-dns-client/0.23.0/trust_dns_client/client/struct.AsyncClient.html#method.new

And you'll need to pass in a "signer" for either SIG0 or TSIG. It's kind-of a misnomer that this is "DNSSEC", those just happen to be overlapping dependencies between the code for DNSSEC validation and the SIG0/TSIG implementations.

**Comment by dainslef** [comment]
> https://docs.rs/trust-dns-client/0.23.0/trust_dns_client/client/struct.AsyncClient.html#method.new

It helps a lot. thank you!
