### ISSUE TITLE
read_system_conf returns different Error types on unix vs windows

### ISSUE THREAD

**Issue by seanmonstar** [bluejekyll/trust-dns#2044]
**Describe the bug**
On Windows, `read_system_conf()` has the return type `ResolveResult<(ResolverConfig, ResolverOpts)>`, whereas on Unix, it has the return type of `io::Result<(ResolverConfig, ResolverOpts)>`.

Is this intentional? If so, should users expect to use `#[cfg]` to handle the difference in types?

**Version:**
Crate: resolver
Version: 0.23.0

**Additional context**
Noticed here: https://github.com/seanmonstar/reqwest/issues/1991

**Comment by djc** [comment]
Probably more like an oversight. Proposed fix in #2047.
