### ISSUE TITLE
Unable to build without linking against libssl/libcrypt

### ISSUE THREAD

**Issue by cbgbt** [bluejekyll/trust-dns#2046]
**Describe the bug**
Even with a minimal set of features enabled, binaries still link against `libssl` and `libcrypt`.

**To Reproduce**

```bash
$ cargo build --no-default-features --features 'resolver,sqlite'
```

This fails to build if openssl lib/headers aren't installed, and produces a library that dynamically links against them if they are.

**Expected behavior**
I anticipated that this would successfully build on a system without openssl dynamic libraries and headers.

**Version:**
Version: 0.23.0

**Additional context**
I believe, though haven't confirmed, that this is due to unconditional openssl dependencies in the workspace root ([e.g.](https://github.com/bluejekyll/trust-dns/blob/ee530bf7496f75e83d368a102502cd902d618ee6/Cargo.toml#L60)).

I'm happy to look into conditionalizing this, I just wasn't sure if I was missing something.

**Comment by cbgbt** [comment]
I went to take a look at this and realized that it's actually not true of the `main` branch. I haven't worked out why that is yet, but this issue isn't necessary. Thanks!

**Comment by djc** [comment]
This is building the binary? There may be some incorrect dependency edges that got cleaned up in #2028.
