### ISSUE TITLE
Figure out a way to merge coverage reports on Coveralls.io

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#229]
Or switch to a different solution. Currently I believe a lot of coverage is being missed as the various feature tests aren't being captured.

**Comment by briansmith** [comment]
I use coveralls for *ring* and I do merge the coverage reports. However, I've found that I often get emails saying that coverage is ridiculously low during CI runs; presumably, this is because they send emails before they do the merging.

**Comment by bluejekyll** [comment]
Well. The coverages report didn’t go up as much as I hoped. It looks like a lot of my #[ignore] tests are driving coverage in some areas down. If I can I’ll try and move those out to integration tests.
