### ISSUE TITLE
[Server] Please add support for CAA records

### ISSUE THREAD

**Issue by Darkspirit** [bluejekyll/trust-dns#234]
https://github.com/bluejekyll/trust-dns/blob/master/proto/src/rr/record_type.rs#L43

I would like to set ones here: http://dnsviz.net/d/dev.terrax.net/dnssec/ (trust-dns)
for https://github.com/TerraX-net/terrax

**Comment by Darkspirit** [comment]
acme.sh:
> [Mon Oct 16 00:31:53 CEST 2017] dev.terrax.net:Verify error:DNS problem: SERVFAIL looking up CAA for dev.terrax.net


https://community.letsencrypt.org/t/caa-servfail-changes/38298/4
> We’ve now removed the exceptions list that roland mentioned in his initial message. SERVFAILs for CAA are now treated as failures for all domain names. See https://letsencrypt.org/docs/caa/62 for details on diagnosing and fixing CAA SERVFAIL problems.

I would like to add this to the zone file:
```
@      CAA 128 issue "letsencrypt.org"
@      CAA 128 iodef "mailto:hostmaster@terrax.net"
```
128 is the CAA critical bit, 0 is the default.

**Comment by rushmorem** [comment]
I need this for Let's Encrypt as well.

**Comment by bluejekyll** [comment]
RFC for this: https://tools.ietf.org/html/rfc6844

I'm looking into this, as this is something I'd very much like to support.
