### ISSUE TITLE
[Server] Please add support for TLSA records

### ISSUE THREAD

**Issue by Darkspirit** [bluejekyll/trust-dns#235]
https://github.com/bluejekyll/trust-dns/blob/f4d8ae1f512796b8ac1ea47f8b27e6849c03b407/proto/src/rr/record_type.rs#L93

http://dnsviz.net/d/dev.terrax.net/dnssec/ (trust-dns)
should get  one `_443._tcp.dev.terrax.net. TLSA ` record
for https://github.com/TerraX-net/terrax

This is just a [habit](https://www.hardenize.com/report/terrax.net#www_dane) and not urgent. :see_no_evil: :four_leaf_clover:

**Comment by bluejekyll** [comment]
Do you need txt forms as well? That is capable of being read from zone file?

**Comment by Darkspirit** [comment]
@bluejekyll
> Do you need txt forms as well? That is capable of being read from zone file?

I do not understand.
TXT records work:
```
dig TXT dev.terrax.net @dev.h.terrax.net +short
"v=spf1 -all"
```

A TLSA response looks like this:
```
dig TLSA _443._tcp.terrax.net @gw1.h.terrax.net +short
3 1 2 D0CC2F9957558D118CAA9DECF07911DA87DC1B3B57AA1EEB6F4DA9F3 F45DB1D1C5F4A1F72A14491032CFEFF931DE6BB8104AE390FA6118CF 29F0E81572AE9E33
```


current zone file:
```
; replace the trust-dns.org with your own name
@               IN      SOA     dev.h.terrax.net. hostmaster.terrax.net. (
                                201709264       ; Serial
                                28800   ; Refresh
                                7200    ; Retry
                                86400  ; Expire
                                600)  ; Minimum TTL
                        NS      dev.h.terrax.net.

@                MX 0 .
@                AAAA 2a01:4f8:c0c:2c12::50
@                TXT "v=spf1 -all"
```
So I would try to add a line like this (this issue it about this):
```
_443._tcp        TLSA 3 1 2 d0cc2f9957558d118caa9decf07911da87dc1b3b57aa1eeb6f4da9f3f45db1d1c5f4a1f72a14491032cfeff931de6bb8104ae390fa6118cf29f0e81572ae9e33
```

The current named binary is from 2017-10-02 (https://github.com/bluejekyll/trust-dns/pull/215#issuecomment-333413205). 🙈

**Comment by bluejekyll** [comment]
Apologies. I meant text forms, such that you put into a zone file. I assume yes.

**Comment by bluejekyll** [comment]
RFC: https://tools.ietf.org/html/rfc6698
