### ISSUE TITLE
Requests for unsupported types time out

### ISSUE THREAD

**Issue by rushmorem** [bluejekyll/trust-dns#243]
For example

```bash
$ dig @localhost -p 5050 CAA example.com +tcp
```

returns the following error message

```
;; Connection to 127.0.0.1#5050(127.0.0.1) for example.com failed: connection refused.
```

*NB*: This is from a minimal custom server based on version `0.12.0` using an empty `Catalog` as the request handler.

**Comment by Darkspirit** [comment]
Maybe at least returning some sort of response  for all RFC'd types listed here: https://github.com/bluejekyll/trust-dns/blob/master/proto/src/rr/record_type.rs#L32 (and keep ignoring unknown types)?

**Comment by rushmorem** [comment]
Aren't we supposed to simply return with [NotImp](https://docs.rs/trust-dns/0.12.0/trust_dns/op/response_code/enum.ResponseCode.html#variant.NotImp) in cases like these?

**Comment by bluejekyll** [comment]
Thanks for the report. NotImp may not be the best option in this case, it’s prbably better to just return an empty recordset. My guess is that the code is hitting an error on the record type parsing and then bailing on the request.

So that code path should be fixed.
