### ISSUE TITLE
Verify no resource leak in MIO and event registry

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#25]
The current methods coded around portability issues with Mac OS X and Linux (Windows, is unknown) where register, reregister and deregister are not acting as expected. See comments in code.

**Comment by phillipCouto** [comment]
Wouldn't this be wiped out by #32?

**Comment by bluejekyll** [comment]
Possibly. this was really a concern I had with early usage of MIO, it's probably not really worth tracking against this project. Also, MIO has gotten a significant amount attention recently, so I'm a lot less concerned.

I'll close for now.
