### ISSUE TITLE
Replace `chrono` dependency with libstd dependency in -client

### ISSUE THREAD

**Issue by briansmith** [bluejekyll/trust-dns#258]
`-client` only depends on `chrono::Duration` from the `chrono` package. There exists a `std::time::Duration` with similar, but not exactly the same, functionality. In #257 I removed the `chrono` dependency from `-proto`. A similar change should be made in -client, to minimize dependencies, especially third-party dependencies.

**Comment by bluejekyll** [comment]
when this was originally written, I believe I needed features in `chrono` that did not exist in `std`. Looks like that's all better now.

**Comment by darnuria** [comment]
Hi, while making some easy-first-good pick locked and this one was closed by 3becddb54b85a3e0848fb50d9a04a051f86dca7f

```
- (all) removed `chrono` dependency #1569
```

**Comment by djc** [comment]
Thanks!
