### ISSUE TITLE
Questionable implementation of DNSClass -> u16 conversion

### ISSUE THREAD

**Issue by briansmith** [bluejekyll/trust-dns#263]
`DNSClass::OPT`s are constructed using code like this, that reads the value from the wire:

```rust
DNSClass::for_opt(try!(decoder.read_u16()))
```

Thus, the value within a `DNSClass::OPT` can be any value in [0, 65535], and the peer chooses that value, so it is attacker-controlled.

Now consider the implementation of `DNSClasss` -> u16 conversion:

```rust
impl From<DNSClass> for u16 {
    fn from(rt: DNSClass) -> Self {
        match rt {
            DNSClass::IN => 1,
            DNSClass::CH => 3,
            DNSClass::HS => 4,
            DNSClass::NONE => 254,
            DNSClass::ANY => 255,
            DNSClass::OPT(version) => version,
        }
    }
}
```

This has a collision for values {1, 3, 4, 254, 255} of version.

Now consider the `Ord` implementation for `DNSClass`:

```rust
impl Ord for DNSClass {
    fn cmp(&self, other: &Self) -> Ordering {
        u16::from(*self).cmp(&u16::from(*other))
    }
}
```

This is using the colliding `DNSClass` -> `u16` conversion.

In turn, the `Ord` implementation is used for the purposes of determining the canonical order of records in a record set. DNSSEC requires us to sort records in the canonical order. However, there's no way that we're guaranteeing that things are in the canonical order here, because of the collision. Because of #200, this broken sorting logic is used not just for signing, but also for verifying DNSSEC-signed record sets.

I don't see any attack that can make use of this + #200, but this is definitely buggy.

The solution is probably to rewrite the `Ord` implementation of `DNSClass` to not use the buggy `DNSClass` -> `u16` conversion. Probably we should also remove the buggy conversion function itself.

**Comment by briansmith** [comment]
Note that test `test_order()` doesn't consider `ORD`. If it did, we would probably have discovered this bug at the time that test was written.

**Comment by bluejekyll** [comment]
This is a great catch!

**Comment by bluejekyll** [comment]
Reopening... The Opt max_data_length should never be less than 512 (i.e. original DNS max packet length). This will actually fix the concern of this issue.
