### ISSUE TITLE
Wildcard is not handled correctly when verifying RRset

### ISSUE THREAD

**Issue by SAPikachu** [bluejekyll/trust-dns#28]
In [`Signer::determine_name`](https://github.com/bluejekyll/trust-dns/blob/master/src/rr/dnssec/signer.rs#L528), only one label is stripped if `num_labels < fqdn_labels`, but according to [RFC 4035 5.3.2](https://tools.ietf.org/html/rfc4035#section-5.3.2), we should keep only `rrsig_label` label. This will break if there are more than 1 label in the wildcard part of domain. [Appendix C.6](https://tools.ietf.org/html/rfc4035#appendix-C.6) describes an example of this case.

**Comment by bluejekyll** [comment]
Ah, you're right. I screwed that up. That one will have to wait for tomorrow.
