### ISSUE TITLE
trust_dns_server: `Message` not re-exported from `proto` crate.

### ISSUE THREAD

**Issue by vi** [bluejekyll/trust-dns#306]
README tells that trust-dns-proto is "not intended for end-user use.".
But to use `trust_dns_server::server::RequestHandler`, one needs `trust_dns_proto::op::message::Message`.
I expected it (along with other relevant types) to be re-exported in `trust_dns_server`, but it seems to be not the case.

This forces users to depend also on `trust_dns_proto` if they want to depend on `trust_dns_server` in order to implement a DNS server. Or is the only "indended for end-user" usage is though the `trust_dns_server::authority::Catalog`?

**Comment by bluejekyll** [comment]
Ah, this is a great point. We should probably come up with a proto prelude which the resolver, client and server all reexport that prelude.

**Comment by bluejekyll** [comment]
proto is now reexported in-total.
