### ISSUE TITLE
Is trust_dns_server sync or async?

### ISSUE THREAD

**Issue by vi** [bluejekyll/trust-dns#308]
One one hand I see refences to Tokio and things.

On the other, `trust_dns_server::server::RequestHandler`'s `fn handle_request(&self, request: &Request) -> Message` returns plain `Message` instead of `Future<Message>`, so expected to be instantaneous. How then should one implement proxies or replicated servers or something like that? Or does it happen in some thread pool?

In any case the documentation should be extended.

**Comment by bluejekyll** [comment]
The server hasn't gotten a lot of treatment to be used internally, or be exposed to be used inside other software at the moment. I do see the value in this, but it's not be high priority at the moment. You're correct that a lot of the library keeps internal references to the reactor::Core and and other async components.

I'd be happy to start making the server easier to use inside other libraries, so if you have changes you'd like to see to make that easier, let's definitely file issues for that use case.

**Comment by bluejekyll** [comment]
This is a duplicate of #309

**Comment by vi** [comment]
So the answer is "it is async, but need to fix some issues".
