### ISSUE TITLE
The RequestHandler should return a future

### ISSUE THREAD

**Issue by vorner** [bluejekyll/trust-dns#309]
In many cases, the server doesn't know the answer right away ‒ it needs to ask a database, compute it in a CPU pool or ask another server. For such situation, returning a future instead of an answer is more appropriate and it shouldn't be a big issue for the ones that have the answer ready.

As discussed OOB, this is probably simple enough in itself, but brings further considerations ‒ like what to do when the future returns error (probably ServFail) and if there should be some timeout on the future's processing.

This is also mentioned in #308, but that one is more of a question than an actionable point.

**Comment by bluejekyll** [comment]
As part of #674 the downstream request is now a future:

https://github.com/bluejekyll/trust-dns/blob/fbfbebe07aa88f914770247c4a49d3ae1a543d33/crates/server/src/authority/catalog.rs#L76-L80
