### ISSUE TITLE
Making the ServerFuture an actual future

### ISSUE THREAD

**Issue by vorner** [bluejekyll/trust-dns#310]
Currently, the ServerFuture creates its own `Core`. This is a common anti-pattern in many crates that they insist on creating their own core, which means if I want to have multiple ServerFuture's, or a ServerFuture and hypers HTTP server in one process, each needs to have its own thread.

The better way would be for the ServerFuture to actually *be* a future (maybe something like `Future<Item = (), Error = io::Error>`. That way I could create the server, compose it within some larger future (shutdown & error handling, for example) and spawn it onto my own core.

**Comment by bluejekyll** [comment]
As an aside, the reason for this is baked into the history of the project. I was never clear to me that people might want to have the DNS Server be a library, but of course that was short sighted... It should be fairly easy to refactor the ServerFuture to move the `Core` out and possibly the `core.run` into the named binary itself to drive it.

**Comment by DemiMarie** [comment]
@bluejekyll I can think of several reasons; for instance, one might want to have a single process containing a DNS server, an SMB server, an LDAP server, and a Kerberos KDC, so that a single process can act as a complete Windows domain controller.

**Comment by bluejekyll** [comment]
I can definitely see the value in doing this. I’ve planned on doing this work, but just haven’t gotten the time. I agree that it should be done.

**Comment by bluejekyll** [comment]
And that’s a really neat idea.

**Comment by bluejekyll** [comment]
I'm going to close this, as I think the ServerFuture and other supporting types like Catalog and Authority are in good shape for any Async work needed. We can reopen, or open another issue if changes are desired.
