### ISSUE TITLE
Heavy-weight errors

### ISSUE THREAD

**Issue by vorner** [bluejekyll/trust-dns#318]
Hello

I believe it makes little sense to mandate that every error in that crate has a backtrace on it, eg: https://docs.rs/trust-dns-proto/0.2.0/trust_dns_proto/error/struct.ProtoError.html.

I think so for two reasons:

* Failing to parse some data that arrived over network has no reason to contain a backtrace.
* The generation of a backtrace isn't cheap and this could be misused by an external entity to eg. DOS the server.

**Comment by bluejekyll** [comment]
There is also a discussion I've had on switch to the `Failure` traits and away from `error-chain`. I'm open to reducing the backtrace usage, though it is useful for debugging issues. Perhaps we should make it a feature that is on or off by default.

**Comment by vorner** [comment]
Well, the Failure could work. The backtrace is optional there (the error is free to not provide it) and the `Error` there does a snapshot of the stack, but resolves the backtrace only if it gets actually produced, so even that is much more light weight.

**Comment by DemiMarie** [comment]
I’ll take this for a school project.

**Comment by bluejekyll** [comment]
#326 is the issue to migrate to failures.

I implemented my first failure resently. It may not be an obvious transition in some cases. Definitely reach out for help, you’re going to run into some old ugly code in spots.

**Comment by briansmith** [comment]
This was fixed in PR #416.

**Comment by bluejekyll** [comment]
This was fixed completely with the conversion to Failure.
