### ISSUE TITLE
Incorrect truncation

### ISSUE THREAD

**Issue by vorner** [bluejekyll/trust-dns#319]
This seems to be wrong: https://docs.rs/trust-dns/0.13.0/trust_dns/op/struct.Message.html#method.truncate. I haven't read the RFCs in a while, so I don't remember which one it was, but as I remember, the idea with truncation was to put as much as fits into the message (depending on the size of the buffer).

AFAIK it is usually done during writing of the message to the output buffer ‒ it is being written from the beginning and if something doesn't fit, it returns back and flips the bit.

**Comment by bluejekyll** [comment]
Yes, we could definitely be a little less aggressive on the truncation. I think the size of the output buffer should respect EDNS. After that, we can then implement what you suggest. It will require some trimming of the outbound buffer. I have some new methods coming on BinEncoder that should make this easier.
