### ISSUE TITLE
shortcut localhost TLD in resolver

### ISSUE THREAD

**Issue by briansmith** [bluejekyll/trust-dns#323]
The following logic from https://tools.ietf.org/html/rfc6761#section-6.3 should be implemented:

> The domain "localhost." and any names falling within ".localhost."
   are special in the following ways: [...]
>
>   2.  Application software MAY recognize localhost names as special, or
       MAY pass them to name resolution APIs as they would for other
       domain names.
>
>   3.  Name resolution APIs and libraries SHOULD recognize localhost
       names as special and SHOULD always return the IP loopback address
       for address queries and negative responses for all other query
       types.  Name resolution APIs SHOULD NOT send queries for
       localhost names to their configured caching DNS server(s).
>
>   4.  Caching DNS servers SHOULD recognize localhost names as special
       and SHOULD NOT attempt to look up NS records for them, or
       otherwise query authoritative DNS servers in an attempt to
       resolve localhost names.  Instead, caching DNS servers SHOULD,
       for all such address queries, generate an immediate positive
       response giving the IP loopback address, and for all other query
       types, generate an immediate negative response.  This is to avoid
       unnecessary load on the root name servers and other name servers.

Further, if the application attempts to configure `localhost` to refer to anything other than the loopback interface, the configuration should be rejected, or the localhost configuration should be silently ignored w/ a warning.

**Comment by briansmith** [comment]
Actually, my "Further" comment is addressed on the next page of the RFC:

> 5.  Authoritative DNS servers SHOULD recognize localhost names as
       special and handle them as described above for caching DNS
       servers.
>
>   6.  DNS server operators SHOULD be aware that the effective RDATA for
       localhost names is defined by protocol specification and cannot
       be modified by local configuration.

**Comment by bluejekyll** [comment]
For localhost, my current practice is to register the `localhost.` zone via configuration in the server. I'm trying to decide if we're going to want a different binary and crate for this mDNS responder, of if we can just use the Server crate.

**Comment by bluejekyll** [comment]
> and cannot be modified by local configuration.

currently the zone configuration with the trust-dns authoritative server is to allow this to be managed through zone configuration. This implies that it should be hard-coded in the authority, and not allow admins to adjust it.

**Comment by briansmith** [comment]
> This implies that it should be hard-coded in the authority, and not allow admins to adjust it.

Exactly. I think any explicit configuration for localhost or *.localhost should be rejected.
