### ISSUE TITLE
Hi, I would like to collaborate with your project by serving as a translator into Spanish, which is my native language

### ISSUE THREAD

**Issue by LuigiBaute** [bluejekyll/trust-dns#349]

**Comment by bluejekyll** [comment]
Excellent! Thank you for the offer. I’ve been considering creating a new repo in the trust-dns github organization for documentation.

I don’t have a lot of experience with internationalization efforts around documentation and how best to organize it. Do you have any thoughts here?

I was thinking it would be fun to use one of the Rust static site generators for this, but I haven’t evaluated it yet...

**Comment by LuigiBaute** [comment]
I believe that a spanish translation would help you to reach spanish talking people, and honestly I don't know about Rust static tho...
