### ISSUE TITLE
Remove panic!() from op_code From impl

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#36]
https://github.com/bluejekyll/trust-dns/blob/master/src/op/op_code.rs#L99

Might need to change away from the From trait and move towards a parser.

**Comment by alserio** [comment]
Hi, just a quick note. The [From trait documentation](https://doc.rust-lang.org/std/convert/trait.From.html) explicitely says:

> Note: this trait must not fail. If the conversion can fail, use TryFrom or a dedicated method which returns an Option<T> or a Result<T, E>.

**Comment by bluejekyll** [comment]
Yes, I'm aware of that restriction. I'll most likely be dropping the usage of that trait in this context in order to fix this bug.

**Comment by bluejekyll** [comment]
Fixed in #42
