### ISSUE TITLE
More than a sec to resolve a query in localhost

### ISSUE THREAD

**Issue by RCasatta** [bluejekyll/trust-dns#367]
Hi,

I am trying out 7714b1147434845db1f28a0df16a9d90b163a8ff on Mac OS X and Ubuntu 16.04, launching with:

`$ ./target/release/named -c server/tests/named_test_configs/example.toml -z server/tests/named_test_configs/ -p 24141`

and then 

`$ time dig @localhost -p 24141 www.example.com`

and it takes more than a second (real	0m1.027s) to resolve

**Comment by bluejekyll** [comment]
Also, I notice in reproducing your results, dig is much faster if you explicitly put `127.0.0.1`. The reason this would be the case is that first dig is making a system call to lookup `localhost` with the system resolver and then it's looking up `www.example.com.` with the `trust-dns` server.

I've never benchmarked with dig or host, and I don't think those are the best tools for benchmarking DNS performance. If that is something you're interested in doing, It would be interesting to get some independent tools for perf testing the server. The benchmarks in the library make use of the `trust-dns` client, which may bias and they are definitely narrow in what they are testing.

**Comment by RCasatta** [comment]
> Also, I notice in reproducing your results, dig is much faster if you explicitly put 127.0.0.1. The reason this would be the case is that first dig is making a system call to lookup localhost with the system resolver and then it's looking up www.example.com. with the trust-dns server.

yes, `localhost` was the issue... Much faster with `127.0.0.1` like 31ms

I launched `cargo +nightly bench` anyway and on Mac OS X mid 2014 laptop I got

```
test trust_dns_tcp_bench      ... bench:      96,494 ns/iter (+/- 2,536)
test trust_dns_udp_bench      ... bench:      82,944 ns/iter (+/- 23,888)
```

I feel the two command initial command I launched could be interesting in the Readme.md after the Running section for a quick test drive, would you like I make a PR?

**Comment by bluejekyll** [comment]
Sure! That would be great!

**Comment by RCasatta** [comment]
When I tried to build the repo I found the target dir in the base dir, not in the server or client dir 

Is my configuration or is the readme outdated?

**Comment by bluejekyll** [comment]
The Readme may be outdated. That was probably written before the projects were moved into a single workspace. After doing that, there is a shared target repo at the root.

**Comment by RCasatta** [comment]
https://github.com/bluejekyll/trust-dns/pull/369
