### ISSUE TITLE
Add alternative default configs for different public resolvers

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#368]
Currently the default configuration is to use Google. See: https://medium.com/@nykolas.z/dns-resolvers-performance-compared-cloudflare-x-google-x-quad9-x-opendns-149e803734e5

Also, if we start including latency measurements in the `NameServerPool` then we can even have all registered, and incorporate latency into the decision on ranking each to the top.

**Comment by lnicola** [comment]
I'm considering running `trust-dns` myself (for DNS over TLS), but I don't have much experience with configuring DNS servers.

> Currently the default configuration is to use Google.

Looking at https://github.com/bluejekyll/trust-dns/tree/master/server/tests/named_test_configs, I didn't see any sample config that uses Google. Can you nudge me a little in the right direction for the simplest possible setup?

**Comment by bluejekyll** [comment]
Quad9 and Cloudflare are now supported.
