### ISSUE TITLE
Add trait for `ResolverFuture` to make mocking of the trust-dns-resolver easier 

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#379]
To make mocking of the trust-dns-resolver library easier in testing, it would be nice to move the ResolverFuture over to a trait.

See: https://github.com/bluejekyll/mock-tdnsr/blob/master/src/main.rs#L16

**Comment by darnuria** [comment]
Resolved before 749f8eccd0dac5c940aa198b3c464d7a7954b14b and #487 even get renamed.

- `ResolverFuture` renamed to `AsyncResolver` #487 (@hawkw)
