### ISSUE TITLE
Feature request: RFC 7858, DNS over TLS

### ISSUE THREAD

**Issue by farrokhi** [bluejekyll/trust-dns#38]
I just finished reading your article about this implementation and noticed that you are working on DNSCrypt integration. I thought maybe it would be a better idea to be the first project to put support for [RFC 7858](https://tools.ietf.org/html/rfc7858) (DNS over TLS) in a production grade client/server.

**Comment by bluejekyll** [comment]
I was looking at that. It looks like it would definitely be capable of covering the same use case. I definitely have some issues with DNSCrypt, what I like about this is I can make use of more off-the-shelf tools.

One advantage of DNSCrypt is that it supports UDP. It looks like the UDP portion of DNSoD is still in draft form, but making progress.

Maybe this would be a good thing to target. I'll look into it.

**Comment by bluejekyll** [comment]
FYI, working on this now. It shouldn't be difficult to get this done client side, server side will take longer to get proper configs ready.

**Comment by bluejekyll** [comment]
End-to-end TLS done. I added some ease of use stuff to the OpenSSL library, I'll see if that gets accepted. I can continue on with integrating into the server configuration. Progress can be tracked in https://github.com/bluejekyll/trust-dns/tree/dns_over_tls

**Comment by bluejekyll** [comment]
Just pushed server side implementations. Tests are forth-coming.

If anyone would care to review, I'd definitely appreciate it.

**Comment by bluejekyll** [comment]
macOS support is done through the use of native-tls, and security-framework. I still need to get Linux support done, which requires an abstraction over some of the certificates on the client and server side.

**Comment by bluejekyll** [comment]
I've run into some issues on the Linux side. If anyone is interested in helping me figure this out, that would be awesome:

https://github.com/sfackler/rust-native-tls/issues/20

**Comment by bluejekyll** [comment]
Ok, fixed in the rust-openssl library: https://github.com/sfackler/rust-openssl/pull/582

**Comment by bluejekyll** [comment]
landed in master... I'll be working on a 0.10.0 release.
