### ISSUE TITLE
dns_sd::tests::test_list_services panics on my machine

### ISSUE THREAD

**Issue by luser** [bluejekyll/trust-dns#393]
I saw your users.rlo post and thought I'd try it out locally, but the test fails for me:

```
$ cargo test -v --features mdns test_list_services -- --nocapture --ignored
<...>
running 1 test
thread 'dns_sd::tests::test_list_services' panicked at 'There is more than one message in the response, this code path needs to deal with that', proto/src/xfer/dns_response.rs:45:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
test dns_sd::tests::test_list_services ... FAILED
```

I have a lot of devices on my home network, so I'm not sure what exactly is causing the problem. If there's any useful info I can provide to help you narrow this down I'm happy to do so.

**Comment by bluejekyll** [comment]
You hit a spot where I was trying to keep the fact that mDNS clean dirtying all the other lookups with multiple messages. I’m not sure why, as I thought I had that clean, but I’ll take a look when I have a minute. I’ll get some more responding on my network and see if I can reproduce.

Thanks for the report!

**Comment by bluejekyll** [comment]
if you rerun with `BACKTRACE=full` that should give us the backtrace to the actual panic path.

**Comment by luser** [comment]
This no longer panics on my machine, thanks! (I don't know if it's accurately presenting all of the results.)

```
running 1 test
service: lockbox2._http._tcp.local.
service: SRV {
    priority: 0,
    weight: 0,
    port: 5000,
    target: Name {
        is_fqdn: true,
        labels: [
            lockbox2,
            local
        ]
    }
}
info: {
    "serial": Some(
        "1750PDN017500"
    ),
    "version_major": Some(
        "6"
    ),
    "version_build": Some(
        "15266"
    ),
    "version_minor": Some(
        "1"
    ),
    "admin_port": Some(
        "5000"
    ),
    "mac_address": Some(
        "00:11:32:6d:aa:cf|00:11:32:6d:aa:d0"
    ),
    "vendor": Some(
        "Synology"
    ),
    "secure_admin_port": Some(
        "5001"
    ),
    "model": Some(
        "DS918+"
    )
}
ip: fe80::211:32ff:fe6d:aacf
ip: 192.168.1.31
service: OctoPrint\040instance\040on\040octopi._http._tcp.local.
service: SRV {
    priority: 0,
    weight: 0,
    port: 80,
    target: Name {
        is_fqdn: true,
        labels: [
            octopi,
            local
        ]
    }
}
info: {
    "path": Some(
        "/"
    )
}
ip: fe80::ba27:ebff:fee1:22e7
ip: 192.168.1.194
test dns_sd::tests::test_list_services ... ok
```

**Comment by bluejekyll** [comment]
It’s definitely possible. There are a lot of things that could be going on. If there is another mDNS responder running on the node, we might not be getting everything to the socket where trust-dns is running.

This impl is definitely experimental, so if you want to help debug why we might be dropping information that would be great.

For the mDNS responder issue we can set a flag in the message to respond directly to the UDP port. That’s described in the RFC and might make responses more reliable at the potential cost of more network traffic.

**Comment by luser** [comment]
I don't know much about mDNS but I'm handy with Wireshark and have a working knowledge of network and system programming, so I'm happy to provide any info or do any testing that would be helpful!

**Comment by bluejekyll** [comment]
I didn't know much about mDNS when I started this, which also probably means that I got some things wrong :)

In fact, I just noticed a bug rereading the RFC: https://tools.ietf.org/html/rfc6762#section-19

`* uses the TC bit in a query to indicate additional Known Answers`, I definitely look for the query_id on all responses still. 

I wonder if the query-id is not being set in some responses: #395

And this is the bit that might need to be set if there is another active mDNS responder on the same system: https://tools.ietf.org/html/rfc6762#section-18.12

There are lots of fun corner cases here :(
