### ISSUE TITLE
Server hangs on any malformed UDP packet

### ISSUE THREAD

**Issue by krant** [bluejekyll/trust-dns#403]
Steps to reproduce:
```
$ cd server
$ ../target/release/named -c ./tests/named_test_configs/example.toml -z ./tests/named_test_configs/ -p 24141
```
in another console:
```
$ dig @127.0.0.1 -p 24141 www.example.com
<works>
$ echo "hello" >/dev/udp/127.0.0.1/24141
$ dig @127.0.0.1 -p 24141 www.example.com
<hangs>
```

**Comment by bluejekyll** [comment]
In your Cargo.lock file, can you grep for tokio-core and it’s associated version?

**Comment by krant** [comment]
Sure, it is `tokio-core 0.1.16`.

**Comment by bluejekyll** [comment]
Cool. Thanks. I’ll take a look at this later. I don’t have a lot of negative tests in the library, so this is great help, thanks for the submission.

I really need to put a fuzzer on the library.

**Comment by DemiMarie** [comment]
@bluejekyll Could AFL be used?  My understanding is that there is Rust integration somewhere.

**Comment by bluejekyll** [comment]
There are a few fuzzers available in Rust. I filed this issue for it: https://github.com/bluejekyll/trust-dns/issues/97

it references `cargo-fuzz`.

**Comment by bluejekyll** [comment]
Ok, reproduced this with a test in #407 working on a fix

**Comment by bluejekyll** [comment]
Thanks for reporting this. There's now a test case for this. Turned out that the error was escaping the UDP handler, causing the UDP socket to be shutdown.

Thanks again for reporting this.

**Comment by krant** [comment]
Thanks for great software!
