### ISSUE TITLE
It should be possible to use a single DNS configuration/options object for multiple lookups

### ISSUE THREAD

**Issue by briansmith** [bluejekyll/trust-dns#423]
My application reads the configuration files (/etc/resolv.conf, /etc/hosts, etc.) using `trust_dns_resolver::system_conf::read_system_conf()` once at startup. I'd like to reuse the config/opts objects it returns for multiple asynchronous lookups. However, `ResolverFuture::new()` uses move semantics for its `config` and `options` arguments. I think it would be better to have `ResolverFuture::new()` take `Rc<>s` instead.

**Comment by bluejekyll** [comment]
I'm guessing this means that in your use case the resolver is not long lived. I think this is fine. Right now ResolverOpts is fairly cheap, so that's copy. Right now, there are some restrictions on ResolverFuture, which I think will require `Arc`.  Any issue with that?

**Comment by bluejekyll** [comment]
Out of curiosity, why not keep the ResolverFuture itself around instead just the Config? Is there a concern with that?

**Comment by briansmith** [comment]
I agree that I should just reuse the `ResolverFuture`, but it is unclear if I can correctly do so in my project until #430 is resolved. I'm going to close this and I think PR #424 should be closed to,
