### ISSUE TITLE
mdns socket creation should use Handle::current

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#428]
@Keruspe , I was reviewing the Handle docs

For mDNS instead of dirtying the interface, should we just use `Handle::current` and then we won't have the deviation from the other interfaces.

I'm pretty sure that is what's going on with the other Socket creation, just implicitly vs. explicitly.

see https://github.com/carllerche/mio/issues/841#issuecomment-384393244

**Comment by Keruspe** [comment]
I got to the same conclusion yesterday reading the mio issue and the Handle doc, was planning on testing it today, so here we are
