### ISSUE TITLE
`ResolverFuture::lookup_ip()` is not lazy (enough)

### ISSUE THREAD

**Issue by briansmith** [bluejekyll/trust-dns#430]
Futures shouldn't do any work until polled, so that they can support code patterns like this (taken from real code):

```rust
        // Construct the future, expecting nothing will happen yet.
        let lookup = self.resolver.lookup_ip(&name.0);

        // Do something that needs to be done before the lookup
        // is initiated.
        let f = Timeout::new(delay, &self.executor)
            .expect("Timeout::new() won't fail")
            .then(move |_| {
                // OK, now actually start doing the lookup work.
                lookup
            });

        // Wrap the future in a Box, giving it a lifetime that is (potentially)
        // longer than `self`. Because of this lifetime issue, we can't call
        // `self.resolver.lookup_ip(&name.0);` inside the closure above.
        return Box::new(f);
```

`ResolverFuture::lookup_ip()` appears to be doing a lot of work and so it doesn't seem to support this code pattern well.

**Comment by hawkw** [comment]
I'd like to start looking into this issue --- @bluejekyll, are you actively working on this and/or will it interfere with work on #456?

**Comment by bluejekyll** [comment]
I'm not aware of this effecting any other work, and no, I haven't started working on it. I will warn you, I don't know yet how deep this goes... but it could unravel quickly, especially in how timeouts are tracked.

**Comment by hawkw** [comment]
Well, I have [a preliminary branch](https://github.com/bluejekyll/trust-dns/compare/master...hawkw:eliza/lazier-resolver-future?expand=1) making this change. It's rather ugly, so probably needs some more work on my end before it's ready for a PR...
