### ISSUE TITLE
release new version client with new tokio

### ISSUE THREAD

**Issue by ariwaranosai** [bluejekyll/trust-dns#453]
I'm using tokio with trust-dns in my project, but trust dns client from crate is old and still using tokio_core. Although, it's ok for me to use dependencies directly from github.

When will trust dns client release a new version?  It there any roadmap?

**Comment by bluejekyll** [comment]
Yes, I have plans on publishing new versions of all the crates soon. I need to review the diffs on all the interfaces, and do a once-over on some of the other libs, like the TLS implementations (I think they still need some upgrades off tokio-core). But this will be happening, it's at the top of my list. (I've been a little distracted with some other projects at the moment).

I don't see anticipate any major changes from what master is right now, if you want to get started with that.

**Comment by ariwaranosai** [comment]
thanks.

**Comment by bluejekyll** [comment]
fyi, new client was published today on crates.io. thanks for your patience!
