### ISSUE TITLE
Different dns lookup result for same host

### ISSUE THREAD

**Issue by sintanial** [bluejekyll/trust-dns#455]
Sometimes trust_dns_resolver resolve two different result

For example i try to resolve host ```www.kinopoisk.ru```
first result is only ipv6 ```LookupIp(Lookup { rdatas: [AAAA(2a02:6b8::2:105)] })```
after 1 second, i send another request to lookup, and 
second result is only ipv4 ```LookupIp(Lookup { rdatas: [A(87.250.251.105), A(213.180.193.105)] })```

**Comment by bluejekyll** [comment]
Hm, I wonder is this is related to the other issue you filed. I have seen this before when the upstream Resolver’s Cache hasn’t been warmed, it will sometimes flip like this until it caches both record types.

Do you see this issue continually? Or is it after any prolonged periods?

**Comment by bluejekyll** [comment]
I'm hoping this is an artifact of #454

**Comment by bluejekyll** [comment]
@sintanial, are you still seeing this issue with the new release and other changes?

**Comment by sintanial** [comment]
@bluejekyll hello, i will try to test it today and write result ;)

**Comment by sintanial** [comment]
Works perfect, thx for fix ;) very nice library

**Comment by bluejekyll** [comment]
Awesome! Glad to hear it.
