### ISSUE TITLE
[Server] Feature request: Allow custom backends to be used for Authorities/Catalogs

### ISSUE THREAD

**Issue by rushmorem** [bluejekyll/trust-dns#47]
As the title, says. Split out the low level functions into a nice DNS library and then build the server and client crates on top of that library. See https://github.com/bluejekyll/trust-dns/issues/43#issuecomment-251733340 and the comments that follow that one for details.

**Comment by bluejekyll** [comment]
More specifically, I think we want generic traits for many of the core structures which would allow arbitrary implementations to work in various contexts.

Example: Server<C: Catalog>::new(C), where C could be some arbitrary backing datastore.

**Comment by bluejekyll** [comment]
I changed the title, I think it's more accurate to what this request is about, as it was written it sounded like a dup of the library splitup.

**Comment by bluejekyll** [comment]
#167 should be enough for this.
