### ISSUE TITLE
resolver `lookup_ip` block forever when use different tokio runtime.

### ISSUE THREAD

**Issue by cssivision** [bluejekyll/trust-dns#472]
```rust
extern crate futures;
extern crate tokio;
extern crate trust_dns_resolver;

use std::io;
use std::net::IpAddr;

use futures::{future, Future};
use tokio::runtime::current_thread::Runtime;
use trust_dns_resolver::config::{ResolverConfig, ResolverOpts};
use trust_dns_resolver::ResolverFuture;

pub fn other(desc: &'static str) -> io::Error {
    io::Error::new(io::ErrorKind::Other, desc)
}

pub fn resolve(
    host: &str,
    resolver: ResolverFuture,
) -> Box<Future<Item = IpAddr, Error = io::Error> + Send> {
    let res = resolver.lookup_ip(host).then(move |res| match res {
        Ok(r) => if let Some(addr) = r.iter().next() {
            future::ok(addr)
        } else {
            future::err(other("no ip return"))
        },
        Err(_) => future::err(other("resolve fail")),
    });

    Box::new(res)
}

fn main() {
    let mut io_loop = Runtime::new().unwrap();
    let resolver = ResolverFuture::new(ResolverConfig::cloudflare(), ResolverOpts::default());
    let resolver = io_loop.block_on(resolver).unwrap();
    let mut runtime =
        tokio::runtime::current_thread::Runtime::new().expect("failed to launch Runtime");

    println!(
        "{}",
        runtime
            .block_on(resolve("www.google.com", resolver))
            .unwrap()
    );
}
```
`runtime.block_on(resolve("www.google.com", resolver)).unwrap()` will block forever, until i replace `runtime` with `io_loop`, or  drop `drop(io_loop)` before this call, test code below.
```rust
 println!(
        "{}",
        io_loop
            .block_on(resolve("www.google.com", resolver))
            .unwrap()
 );

// --------------------------------------------------
drop(io_loop);
println!(
        "{}",
        runtime
            .block_on(resolve("www.google.com", resolver))
            .unwrap()
 );
```

**Comment by cssivision** [comment]
this issue may related to `tokio`, but i think i should also should post here.

**Comment by bluejekyll** [comment]
Yes. I’m not sure what the solution is here. The Resolver spawns the network handlers onto the first Runtime. Then the lookup futures returned are run in a different runtime, they both must be run or use a single one.

For a multi runtime solution, this example is good: https://github.com/bluejekyll/trust-dns/blob/master/resolver/examples/global_resolver.rs

**Comment by bluejekyll** [comment]
I've been thinking for a little bit that we should restructure the timeout, or perhaps add another timer option on the lookup itself. If we do that, we can timeout on the client side. It doesn't fix the problem, but it would at least always timeout.

**Comment by cssivision** [comment]
the global resolver in the example works, because the `runtime` https://github.com/bluejekyll/trust-dns/blob/master/resolver/examples/global_resolver.rs#L38  dropped after the global resolver init.

**Comment by bluejekyll** [comment]
What's going on there, is that `Runtime::run` doesn't return until all associated futures with that Runtime complete. There are implicit futures associated with the NameServers registered in the NameServerPool that are spawned into the Runtime. The `ResolverFuture` then is returned, and basically contains only channels pointing back to the NameServer futures.

See #464, that discusses what I'd like to do to change this interface to make those interior Futures more explicit. I think it would help avoid the issue you've run into, though it doesn't remove the fact that the Future for the connections is separate from the future for the lookup, that is waiting potentially in another thread.

I'm open to other ideas here, but every time I think through how to make this more ergonomic, I end-up stuck with the problem that the NameServerPool owns the connection, and if you want a ResolverFuture that supports multiple threads you need a model like this... This is partly why I want to hide all this, and create a GlobalResolver, at the expensive of a single resolver thread running the background Runtime.

**Comment by bluejekyll** [comment]
Also. Refer to #479 for a standard multi-threaded example.

**Comment by carllerche** [comment]
@bluejekyll Generally speaking, the strategy for background "worker" tasks is to have some strategy to shutdown automatically when it knows it has no further work to do.

The basic example would be a task that pulls work off of an mpsc channel. In this case, when all the `Sender` handles have dropped, the worker task should shutdown because it can never receive any more work.

The `h2` library has a similar setup as well. There is a `Connection` task that manages the connection and a `SendRequest` handle that can be cloned to issue client requests. Once all `SendRequest` handles have dropped, the `Connection` task starts a graceful shutdown process and then terminates.

**Comment by bluejekyll** [comment]
Yes. The trust-dns libraries are built this way as well. If all channels are closed, the ResolverFuture spawned tasks will also shutdown. Currently this will also shutdown any tcp connections and close udp sockets as well.

The conversation above I think is more about how to guarantee the background tasks are being run before a query is performed.
