### ISSUE TITLE
Add (optional) serde support for types in trust_dns_resolver::config

### ISSUE THREAD

**Issue by kingoflolz** [bluejekyll/trust-dns#490]
Hi,

I am building an application which will use trust-dns-resolver and I would like to have a config file where the user can specify which DNS server to use. Adding serde as an optional dependency and optionally deriving Serialize and Deserialize on the config types would make this much easier. Is this something that you would be interested in adding?

I would be happy to provide a PR for this.

Thanks

**Comment by bluejekyll** [comment]
I'd prefer to not pull a dependency on Serde right now.

It's possible this might work: https://serde.rs/remote-derive.html

Something along the lines of:

```rust
#[derive(Serialize, Deserialize)]
struct TrustDnsConfig(ResolverConfig);
```

See how far that gets you...

**Comment by kingoflolz** [comment]
@bluejekyll using remote derive should work, but I think it will be better to build serde support in so it would be more seamless. We can use a cargo feature to ensure there are no additional deps by default, and people who need it can opt into using serde.

**Comment by bluejekyll** [comment]
@briansmith, I think you’d have the biggest concern here...

**Comment by briansmith** [comment]
> @briansmith, I think you’d have the biggest concern here...

I don't have a good answer. If this were my project I would probably wouldn't do it, just due to lack of time to fully think through all the implications of doing it.

**Comment by bluejekyll** [comment]
Thanks, @briansmith.

@kingoflolz there is this issue:  #483, which may be of interest. I think that might end up needing some serde derivable configs as well. I did add this to the server crate. My concern is that with the resolver we want to keep the dependencies slim as we want it to be able to be embedded in many different contexts, and config files would generally only be for binaries.

I suppose if we keep this as optional, and off by default, then that would be ok, though I am curious what it would look like to have a separate crate for this glue...
