### ISSUE TITLE
DNS Queries over HTTPS (DOH), tracking

### ISSUE THREAD

**Issue by rumpelsepp** [bluejekyll/trust-dns#503]
I just wanted to create a tracking issue for this. Since last month or so, mozilla is experimenting with this.

https://datatracker.ietf.org/doc/draft-ietf-doh-dns-over-https/
https://groups.google.com/forum/#!msg/mozilla.dev.platform/_8OAKUHso0c/QUhjVYz3CAAJ
https://bugzilla.mozilla.org/show_bug.cgi?id=1446404

One could argue that an HTTP library could be used for this; the advantage of having this also in TRust-DNS would be the unification of the API for different transports.

**Comment by rumpelsepp** [comment]
:) Since the RFC is not yet released, I thought it might be useful to have an issue to track its status.

**Comment by briansmith** [comment]
> integrate HttpsClientStream into trust-dns-resolver

It would be great if there could be a way to avoid building HttpsClientStream, and all its dependencies, when building trust-dns-resolver.

**Comment by bluejekyll** [comment]
This will be optional in the Resolver like the dns-over-tls features, and default to off. Do you have more concerns than that?

**Comment by briansmith** [comment]
> This will be optional in the Resolver like the dns-over-tls features, and default to off.

Sounds good.

> Do you have more concerns than that?

Nope!

**Comment by bluejekyll** [comment]
FYI, I think the HttpsClientStream is done. before merging, I'm going to see what some of the underlying changes look like to support in the Resolver.

**Comment by bluejekyll** [comment]
Ok, with #519 there is now a viable implementation of DNS-over-HTTPS in TRust-DNS.

I had to hack around what appears to be a poor abstraction over the IO streams. I want to look into that in a little more detail to see if there is a better solution, so this isn't landing yet.

Also, note that this initial implementation will only support Rustls for the TLS implementation.

**Comment by rumpelsepp** [comment]
Thank you so much for your hard work!

**Comment by bluejekyll** [comment]
That took a while, but #520 is going to be the path to merging. This is gets rid of the unnecessary Vec that was holding all the H2 responses, instead passing that back with a oneshot channel. There's some additional cleanup I want to do, but this is starting to look good.

Once this is all clean, the resolver will be merged, then I'll start working on the server/client.

**Comment by bluejekyll** [comment]
I just merged #520 

This means that master now has dns-over-https support for the Resolver. It currently only works with `rustls` and requires the `dns-over-https` feature to be enabled. I'll open some bugs for supporting the Client and the Server at some point in the future.

**Comment by bluejekyll** [comment]
This was resolved completely in #557
