### ISSUE TITLE
Answers should use original query names, not what's in the catalog

### ISSUE THREAD

**Issue by rushmorem** [bluejekyll/trust-dns#511]
- To preserve case of the original query name
- So as not to return characters such as `*` that may be in the catalog

**Comment by bluejekyll** [comment]
Ah, interesting. This may be in a bit of conflict with the current model of Iterators used for response collection.

**Comment by rushmorem** [comment]
Yeah, I noticed. That should help with memory usage.

**Comment by bluejekyll** [comment]
yes... but it’s probably going to make fixing this a challenge is my point. The easiest place to do this replacement will be close to serialization time...

Maybe there’s an easy wrapper type that can be placed on all answer records that has the associated query? And that can be used for serialization? It could be applied with a map function on the record set lookup...

**Comment by bluejekyll** [comment]
Not sure when exactly this was fixed, but original queries are returned in the response now.
