### ISSUE TITLE
mDNS Responder?

### ISSUE THREAD

**Issue by dan-f** [bluejekyll/trust-dns#515]
I'm wondering if the current implementation of mDNS in this library supports _responding_ to mDNS queries in addition to issuing the queries themselves.

My use case is a p2p application over a local network in which nodes need the ability to advertise themselves as peers.

Thanks!

**Comment by bluejekyll** [comment]
Not yet. I haven't gotten back to support an mDNS responder yet. This is a big goal of mine though...

On top of that some additional debugging needs to happen, as we've noticed that DNS-SD over mDNS isn't capturing entire sets of services on the network, so there are some bugs...

**Comment by dan-f** [comment]
I see, thanks for the update!
