### ISSUE TITLE
Please add support for the new CAA "validation-methods" + "account-uri" parameters

### ISSUE THREAD

**Issue by Darkspirit** [bluejekyll/trust-dns#516]
https://community.letsencrypt.org/t/acme-caa-validation-methods-support/63125
https://tools.ietf.org/html/draft-ietf-acme-caa-04

The parameter value is a comma-separated string:
`@ CAA 0 issue "letsencrypt.org; validation-methods=dns-01,http-01"`

A CA would have to abort if it doesn't support validation-methods:
`@ CAA 128 issue "letsencrypt.org; validation-methods=dns-01"`

I find the backslash (`"letsencrypt.org\; validation-methods=dns-01"`) in the forum post confusing, maybe because I never used bind?

Current error:
> 1529411380.946177:ERROR:named:406:could not load zone dev.terrax.net.: error reading zone: "/home/trustdns/dev.terrax.net.zone": proto error

The following non-standard line is accepted by TRust-DNS because it does not contain hyphens or a comma:
`@ CAA 0 issue "letsencrypt.org; validationmethods=dns01"`

**Comment by bluejekyll** [comment]
Thanks for the report.

**Comment by bluejekyll** [comment]
Ok. Looks like the parsers in https://github.com/bluejekyll/trust-dns/blob/master/proto/src/rr/rdata/caa.rs

For the name field is too strict, we’ll need to review the name field restrictions in the RFC and allow for some additional special characters.

**Comment by Darkspirit** [comment]
https://community.letsencrypt.org/t/caa-validation-methods-invalid-format/63804/2

**Comment by bluejekyll** [comment]
Gotta love the RFC process. ;)

**Comment by bluejekyll** [comment]
The new RFC doesn't even mention the new parsing changes. Which implies to me that they did the wrong thing by introducing `-` in keys of the issuer. I'll allow `-` in the key name, but this will allow non-compliant keys to be introduced in these fields...

**Comment by Darkspirit** [comment]
https://github.com/hardenize/hardenize-public/issues/33
> Relevant thread: https://www.ietf.org/mail-archive/web/acme/current/msg02785.html

**Comment by bluejekyll** [comment]
ok #517 has the fix, this test case should validate these options:

https://github.com/bluejekyll/trust-dns/blob/7315ae1644933d226923a93c30dd0459f775fe8e/proto/src/rr/rdata/caa.rs#L915-L930

**Comment by bluejekyll** [comment]
> Maybe it was good to ask around what should be done now, maybe they find a better solution?

I think it's clear that discussion is already happening. Anyone that strictly implemented the original RFC6844 will also need to upgrade and patch their software, so I suspect they'll want to support something without these additions.

**Comment by bluejekyll** [comment]
@Darkspirit, I think that #517 is good, not sure if you want to test it before I merge into master.

**Comment by Darkspirit** [comment]
> @Darkspirit, I think that #517 is good, not sure if you want to test it before I merge into master.

Thank you! But I don't want to ask you to merge something unstable you might be uncomfortable with, and which could be fixed, since this is still in staging and got attention from some more people now.

https://www.ietf.org/mail-archive/web/acme/current/threads.html#02785
(It sounds like they'd ask to fix it by removing hyphens from labels but keeping them in values?)

**Comment by Darkspirit** [comment]
> test it

[PowerDNS](https://www.hardenize.com/report/terrax.net/1529597993#domain_caa) and [TRust-DNS](https://www.hardenize.com/report/dev.terrax.net/1529597672#domain_caa) now behave the same.

**Comment by Darkspirit** [comment]
It has been fixed:
https://tools.ietf.org/rfcdiff?url2=draft-ietf-acme-caa-05.txt
https://github.com/letsencrypt/boulder/pull/3772/files

**Comment by bluejekyll** [comment]
So I think that at least part of the PR is still needed as the value field was too strict before and didn’t support the url characters.

I think I might just allow the `-`... I’ll think about it.

**Comment by bluejekyll** [comment]
Ok, merging this in.
