### ISSUE TITLE
Security vulnerability in 'untrusted' crate which trust-dns uses

### ISSUE THREAD

**Issue by cswindle** [bluejekyll/trust-dns#522]
When running cargo audit against a crate which uses trust-dns it reports there is a security vulnerability in the version of 'untrusted' create which trust-dns uses:

```
ID: RUSTSEC-2018-0001
Crate: untrusted
Version: 0.3.2
Date: 2018-06-21
URL: https://github.com/briansmith/untrusted/pull/20
Title: An integer underflow could lead to panic
Solution: upgrade to: >= 0.6.2
```

Could you upgrade to 0.6.2 of 'untrusted' so that cargo audit does not flag a failure?

**Comment by bluejekyll** [comment]
Thank you for the report. I’ll try and do this ASAP.

**Comment by bluejekyll** [comment]
@cswindle can you give me the features you're enabling for trust-dns? I'm guessing it's either `dnssec-ring` or `dns-over-rustls`...

As of now, the underlying \*ring\* library is still in alpha: https://crates.io/crates/ring, 0.13 has the upgraded 0.6.1, but I've been hesitant to upgrade until 0.13 stabalizes.

@briansmith, any guidance here?

**Comment by briansmith** [comment]
I would use 0.13-alpha over 0.12 any day, myself. It means everybody using Trust-DNS and using *ring* for anything would need to upgrade to 0.13-alpha too.

**Comment by bluejekyll** [comment]
Ok, I'll work on getting this in: #327

@cswindle do you need this in 0.9 or in master?

**Comment by bluejekyll** [comment]
I’m going to close this as it’s resolved in master. If we need this before the next release, it can be backported to 0.9

**Comment by cswindle** [comment]
I am happy for it to just be in master.
