### ISSUE TITLE
Refactor all uses of `tokio::executor::spawn` into background tasks

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#524]
See Background in resolver.

- [x] `client_future::ClientFuture::with_timeout`
- [x] `name_server_pool::ConnectionProvider::new_connection()`

**Comment by bluejekyll** [comment]
Oh, nice! Thanks for picking this up. We could split this into two different issues, once for name_server_pool and the other for client_future if you want. The name_server_pool one would help clean up some of the Resolver Background stuff you wrote before.

When I was doing some recent refactoring, I was trying to pull a lot of that up the stack...

**Comment by hawkw** [comment]
> We could split this into two different issues, once for name_server_pool and the other for client_future if you want. 

Yeah, that was the plan. I think the `client_future` change is not going to be terribly _difficult_, but it looks like a lot of other code that depends on it will need to be changed as well.

**Comment by bluejekyll** [comment]
Yeah, that makes sense. I also think it makes sense to keep the reconnect logic inside the background task. I think the only thing to consider is to make sure reconnect only is attempted after a poll (lazily) and not (eagerly) immediately after a failure, if that makes sense.

Making the background basically a set of states, Disconnected (start) -> Connected <-> Failed -> Disconnected, or something like that seems like it would make the most sense.

**Comment by hawkw** [comment]
Yeah, that's more or less what I had in mind.

Currently, I'm doing some thinking about how to structure this so that it doesn't introduce an additional `mpsc` channel between a `NameServer` and the connection, but I'm not sure whether or not that will be possible.

**Comment by bluejekyll** [comment]
I just cleaned up a few of those... and yes, it's hard in this context not to need that.
