### ISSUE TITLE
server:  test_example_tls_toml_startup failure

### ISSUE THREAD

**Issue by polyzen** [bluejekyll/trust-dns#527]
```
~/p/b/tr/s/trust-dns-server-0.14.0 > cargo test --release --test z_named_native_tls_tests                                                                                
    Finished release [optimized] target(s) in 0.10s
     Running target/release/deps/z_named_native_tls_tests-ee548df2adb6ab05

running 1 test
test test_example_tls_toml_startup ... FAILED

failures:

---- test_example_tls_toml_startup stdout ----
        using server src path: .
thread 'test_example_tls_toml_startup' panicked at 'failed to start named: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    test_example_tls_toml_startup

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test z_named_native_tls_tests'
```

Edit: Rust 1.27.1

**Comment by bluejekyll** [comment]
Did this start happening after 1.27.1?

I just kicked off a new build, this should pick up 1.27.1: https://travis-ci.org/bluejekyll/trust-dns/builds/402848373

We'll see what's up.

**Comment by bluejekyll** [comment]
It looks like you're running the tests from the crates.io package. I've never tried to do that. I think you're running into an issue where certain resources aren't included in the package, that are available in the git repo. I think we should probably narrow the package contents in the `Cargo.toml` to exclude test directories all together.

**Comment by polyzen** [comment]
> Did this start happening after 1.27.1?

I had not tried prior to this.

> I think we should probably narrow the package contents in the Cargo.toml to exclude test directories all together.

Sounds good to me.
