### ISSUE TITLE
[Tracking] Consider doing a release

### ISSUE THREAD

**Issue by kpcyrd** [bluejekyll/trust-dns#535]
I'm currently depending on the git master of trust-dns, a new release would allow me to merge and release the branch I'm working on.

Thanks! :)

**Comment by bluejekyll** [comment]
I was hoping to finish a few things up before publishing a new release. Would you mind if I published it as an "alpha" release?

I'm currently not in a great spot to push this but will try to ASAP, but it might take a few days.

**Comment by kpcyrd** [comment]
No worries, I just wanted to let you know that there's interest, but there's no hurry. :)

I'm currently using the git master for `trust-dns-resolver`, `trust-dns-server`, `trust-dns-proto` and `trust-dns`, an alpha release should work fine.

**Comment by bluejekyll** [comment]
Ok, just published the alpha version... this will allow me to continue working on the other stuff I want to get into this release without blocking you on some of these dependencies.

**Comment by kpcyrd** [comment]
Awesome, thank you! :) I've started preparing a release as well.
