### ISSUE TITLE
Doesn't build for iOS target

### ISSUE THREAD

**Issue by azdlowry** [bluejekyll/trust-dns#540]
The issue seems to be the use of a very old version of error-chain crate which has a dependency on backtrace crate. Backtrace doesn't build for iOS but later version of error-chain this is an optional dependency.

**Comment by azdlowry** [comment]
Sorry, we're using an old version of trust-dns for some reason.

**Comment by bluejekyll** [comment]
Awesome. Would love to know how you’re using this on iOS, if you ever care to share.
