### ISSUE TITLE
trust-dns-proto docs break

### ISSUE THREAD

**Issue by bspeice** [bluejekyll/trust-dns#544]
I'm unable to build documentation for some of my projects because they pull in trust-dns-proto, and the documentation breaks:

```
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  |
  = help: add #![feature(extern_prelude)] to the crate attributes to enable

error: Could not document `trust-dns-proto`.
```

Is it possible to un-break things? I was under the impression that `#![feature]` flags require using a nightly compiler.

**Comment by bluejekyll** [comment]
To work around the nightly compiler errors, I use stable to generate docs, which works great: `cargo +stable doc`

As to this specific error, I haven’t looked into what would fix it on nightly.

**Comment by bluejekyll** [comment]
Oddly, this used to happen to me often. On nightly and stable, I'm not seeing issues, current nightly:

`rustc 1.29.0-nightly (97085f9fb 2018-08-01)`

Not sure why I can't reproduce this right now.

**Comment by bspeice** [comment]
I was on a 1.30 nightly if it makes any difference.

**Comment by bspeice** [comment]
Re-tried with most recent 1.30 nightly, no longer an issue. Going to consider this closed.

**Comment by bluejekyll** [comment]
Excellent. Thank you for following up!
