### ISSUE TITLE
code size

### ISSUE THREAD

**Issue by aep** [bluejekyll/trust-dns#551]
any chance to make idna and url optional dependencies? it's fairly large

**Comment by bluejekyll** [comment]
I think we could do this. It would mean losing some validation and conversion of international names, and limit us to ascii only name interfaces. I believe it's only in place during Name parsing and Name conversion to Strings.

Basically we could default it to on, and make it optional, then feature flag off the methods that require it.

I think we'd lose these methods when it's not enabled:

https://github.com/bluejekyll/trust-dns/blob/master/proto/src/rr/domain/label.rs#L45
https://github.com/bluejekyll/trust-dns/blob/master/proto/src/rr/domain/label.rs#L139
https://github.com/bluejekyll/trust-dns/blob/master/proto/src/rr/domain/name.rs#L412

And we'd need to limit the Display implementation to remove the condition on internationalization:

https://github.com/bluejekyll/trust-dns/blob/master/proto/src/rr/domain/label.rs#L218-L238

And then make this struct feature flagged off as well:

https://github.com/bluejekyll/trust-dns/blob/master/proto/src/rr/domain/name.rs#L736

I think that's all the places where IDNA is in use.

**Comment by aep** [comment]
thanks so much. i'm rewriting carrier now to replace tokio with mio.

Any chance to put only the dns parser into a separate crate?
trust-dns-proto depends on tokio unfortunately

**Comment by bluejekyll** [comment]
> Any chance to put only the dns parser into a separate crate?

I’ve considered it in the past, but haven’t had a need to do so. The project already has so many crates! For some reason I hesitate to add more...

**Comment by aep** [comment]
no longer relevant, should we close?

**Comment by bluejekyll** [comment]
Eventually I want to rework the library to be generic over futures based implementations, but yes, this we can close.
