### ISSUE TITLE
Listen on all addresses

### ISSUE THREAD

**Issue by rbmj** [bluejekyll/trust-dns#56]
Currently, named doesn't actually listen on all specified addresses.  It takes the first address (both v4 and v6), or a default of `0.0.0.0` and `::0`.  In addition, there's no way to disable IPv4 or IPv6 as even if an IPv4 address is specified the system still will use the default IPv6 address - even if no IPv6 address is set _or_ even if it is explicitly set to the empty list.

This breaks some dual-stack systems as well where `IPV6_V6ONLY` is by default false, because the v6 socket cannot bind as it conflicts with the v4 socket.

The attached patch is my attempt to fix the issue - I haven't tested every edge case, but it works on my system (debian) with the default configuration (example.toml) under simple tests, and seems sane to me.
[0001-Listen-on-all-available-IP-addresses.txt](https://github.com/bluejekyll/trust-dns/files/551371/0001-Listen-on-all-available-IP-addresses.txt)

**Comment by bluejekyll** [comment]
Thanks for submitting this. I'll try and apply the patch you submitted and put up a PR as soon as I can. This might not be for a few days though.

**Comment by rbmj** [comment]
That sounds fine - next time I'll be less lazy and get github to do a proper fork for me.

**Comment by bluejekyll** [comment]
See the commit I just pushed. That incorporates your fix (mostly verbatum, though I made it fail a little nicer).

I wrote a new test harness for the `named` bin, which I had been planning on doing for a while, this gave me a good reason to. Anyway, you can run these tests with `cargo test` or more specifically `cargo test --test z_named_test` to test just ipv4 listeners, and both ipv4 and ipv6. I found at least on my mac that an ipv6 only listener is still routable from ipv4 via the standard ipv4 address mapping to ipv6, not sure if that is true on other OS'

**Comment by bluejekyll** [comment]
I believe that the patch I submitted fixes this. If not please reopen.
