### ISSUE TITLE
What should be iterated with trust_dns_proto::rr::rdata::txt::TXT.iter()?

### ISSUE THREAD

**Issue by kolbma** [bluejekyll/trust-dns#598]
I'm wondering what should be iterated with the [iter()](https://docs.rs/trust-dns-proto/0.5.0-alpha.5/trust_dns_proto/rr/rdata/txt/struct.TXT.html#method.iter) method?

I've thought of split-up the TXT RR for the xyz=abc key-value-pairs separated by comma or semikolon. But I only get back one iteration with the complete TXT RR.

An iterable over multiple TXT RRs is also not the case, because these would be in multiple DnsResponse.answers()?!

So is there a bug and the key-value-pairs should be iterable or what is iterable?

**Comment by bluejekyll** [comment]
This iter is exposing the underlying TXT format from RFC 1035:

https://tools.ietf.org/html/rfc1035#section-3.3.14

It is specified as a blob of one or more character strings, ie:

```text
TXT RDATA format

    +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+
    /                   TXT-DATA                    /
    +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+

where:

TXT-DATA        One or more <character-string>s.

TXT RRs are used to hold descriptive text.  The semantics of the text
depends on the domain where it is found.
```

In the general case, I expect most people only associate a single character string with the TXT record, but the spec allows for any number of character strings in a single record, eg you'll usually only have an iteration with one element. Character strings in DNS are similar to C style strings, but have a length attribute before they are parsed from the binary stream. There is no implicit breaking across boundaries of `=` or spaces or any other delimiter as you've noticed in your experiments. It would require a record to be created with the explicit desire of having more than on character string, which many tools may not make easy, thus most people probably only end up with a single character string.

Hopefully this helps!

**Comment by kolbma** [comment]
Ah. So many thanks, @bluejekyll . Your explanation is great. Didn't get it that it might be possible to put there multiple C strings in the RR. Maybe my DNS server wouldn't also parse files with "\0" in it. But it makes senses now ;-)
