### ISSUE TITLE
Implement draft-ietf-curdle-dnskey-eddsa (EdDSA signatures for DNS)

### ISSUE THREAD

**Issue by briansmith** [bluejekyll/trust-dns#60]
See [draft-ietf-curdle-dnskey-eddsa](https://tools.ietf.org/html/draft-ietf-curdle-dnskey-eddsa).

**Comment by bluejekyll** [comment]
Sweet. We can do this after switching to *ring*

**Comment by bluejekyll** [comment]
I added a new KeyPair type to the client library. This allows for a high level abstraction over different key implementations. We should be able to use it to abstract over different implementations. So adding I looked briefly at rings eddsa and I think it should be easily integrated.

**Comment by bluejekyll** [comment]
@briansmith if you get a chance, can you look at my diff that I just posted? I want to make sure that all that looks legit to you...

**Comment by bluejekyll** [comment]
FYI, I just landed this in main, I'll close this here, though I should probably mark this as experimental until there is external validation.
