### ISSUE TITLE
Please consider committing and publishing Cargo.lock

### ISSUE THREAD

**Issue by polyzen** [bluejekyll/trust-dns#604]
**Is your feature request related to a problem? Please describe.**
Reproducible builds.

`error: the lock file needs to be updated but --locked was passed to prevent this`

**Comment by polyzen** [comment]
> Originally we did include this, but it was removed in #458

Yes, I understand (now) the [FAQ](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) states not to commit `Cargo.lock` for libraries, but seems that's [controversial](https://github.com/raphlinus/pulldown-cmark/pull/152#issuecomment-436061992).

Also it appears you would need to use an ["unstable" feature](https://github.com/rust-lang/cargo/issues/5654).

> Is this related to trying to build named?

Yes.

> In what context is --locked being passed?

Working towards reproducible builds for [Arch Linux](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=trust-dns-server). BTW, is my package inappropriately named since it ships only `named`?

**Comment by bluejekyll** [comment]
I think this is work discussing how to best package this. I'm really quite unfamiliar with proper packaging in system distributions. I think naming the package `trust-dns-server` is fine, but my choice of `named` might become controversial, and we may want to change that.

I'm open to making changes to the structure of the crates and repo to support these distributions, although to be honest, I've planned to continue suggesting people just install directly from cargo. It looks like maybe that's exactly what your arch-linux install does, so that's probably fine. One comment I have, is there are a lot of compile time features that are defaulted to off, and some are experimental at the moment. Specifically, DNSSSEC is defaulted to off, yet it's in the description you have on the arch distribution, I'm not sure how we'd handle making it possible to enable those features.

I have done very little research in this area, so my answers here won't be great, and more likely I'll just keep asking questions ;)

**Comment by bluejekyll** [comment]
> Yes, I understand (now) the FAQ states not to commit Cargo.lock for libraries, but seems that's controversial.

I remember getting a lot of feedback on this, but of course I can't find it now. It was a lot harder to maintain the dependencies under this model, and created downstream issues for (library) users I remember.

**Comment by polyzen** [comment]
> I'm open to making changes to the structure of the crates and repo to support these distributions

> I remember getting a lot of feedback on this, but of course I can't find it now. It was a lot harder to maintain the dependencies under this model, and created downstream issues for (library) users, as I remember it.

If `named` were to be split out into its own crate, the lock file could then be published for that binary crate. There is code (IIUC) to prevent lock files being published otherwise. The lock files would then also be available for the libraries' developers.

> Specifically, DNSSSEC is defaulted to off, yet it's in the description you have on the arch distribution,

Will fix that.

> I'm not sure how we'd handle making it possible to enable those features.

No worries here, as we're meant to ship packages as vanilla as possible.

**Comment by bluejekyll** [comment]
> There is code (IIUC) to prevent lock files being published otherwise.

Do you mean in `cargo publish`?

> The lock files would then also be available for the libraries' developers.

Sorry, by library I think you're referring to the general trust-dns software, not specifically the trust-dns-server library, right?

I think the concern I have right now is that with the current project construction, the lock file would be stored in the root, effecting all the crates, and not just the binary. So we'd need to exclude it from the published artifacts to crates.io for the other crates (something we probably need to slim down anyway). That would be a path forward.

**Comment by polyzen** [comment]
> Do you mean in `cargo publish`?

https://github.com/rust-lang/cargo/blob/0.31.0/src/cargo/sources/path.rs#L346-L349

> Sorry, by library I think you're referring to the general trust-dns software, not specifically the trust-dns-server library, right?
>
> I think the concern I have right now is that with the current project construction, the lock file would be stored in the root, effecting all the crates, and not just the binary. So we'd need to exclude it from the published artifacts to crates.io for the other crates (something we probably need to slim down anyway). That would be a path forward.

Yes, and thank you for the consideration!

**Comment by polyzen** [comment]
> Also it appears you would need to use an ["unstable" feature](https://github.com/rust-lang/cargo/issues/5654).

Mentioned it in passing ^

**Comment by bluejekyll** [comment]
I see. That connects all the dots for me, thanks.

I think the best path forward will be to put the binaries into separate crates. Does this block your path forward? or is this an optimization/stabilization for the arch installation script?

**Comment by polyzen** [comment]
Note: [Publishing the lockfile](https://github.com/rust-lang/cargo/issues/5654) with the server crate is not done yet. Will file an issue or PR once `publish-lockfile` is stabilized.

**Comment by polyzen** [comment]
I don't know, but I have a feeling https://github.com/rust-lang/cargo/blob/0.32.0/src/cargo/sources/path.rs#L347-L350 would make it not possible.

See also https://github.com/sharkdp/diskus/pull/17.

**Comment by polyzen** [comment]
> [Cargo will be changed to always include Cargo.lock in the .crate file if the package has binaries or examples.](https://github.com/rust-lang/cargo/issues/5654#issuecomment-497863987)
