### ISSUE TITLE
How to transform `trust_dns_proto::rr::rdata::mx::MX` into &str or IpAddr?

### ISSUE THREAD

**Issue by paulbnt23** [bluejekyll/trust-dns#607]
Rust beginner here.

```rust
    let hosts = mx_hosts::get_mx_lookup(my_domain);

    for host in hosts.iter() {
        debug!("{:?}", host);
        // I want host either as &str (the dns name) or as IpAddr, is that possible?
    }
```

Thanks.

**Comment by bluejekyll** [comment]
I'm not familiar with the `mx:hosts::get_mx_lookup` function you mention, so I'm going to assume it is calling this function in the Resolver (I'm writing this free form, so apologies if the code I write here doesn't compile as-is):

https://docs.rs/trust-dns-resolver/0.10.0/trust_dns_resolver/struct.Resolver.html#method.mx_lookup

Assuming you have a Resolver already constructed in some manner, `let resolver = Resolver::new...;`

```rust
let mx_lookup = resolver.mx_lookup("example.com.")?;
```

We now have the mx_lookup response, this returns an `MxLookup` which has a function, `iter` which returns an `MxLookupIter`, this can be used to iterate over the MX, which has an `exchange` and `preference` [component](https://docs.rs/trust-dns-proto/0.5.0/trust_dns_proto/rr/rdata/mx/struct.MX.html), records:

```rust
for mx in mx_lookup.iter() {
    let name: &str = mx.exchange();
    let preference: u16 = mx.preference();
}
```

Does that all make sense? After this, you'd generally want to do an `A` or `AAAA` lookup, or use `lookup_ip` which will lookup both A or AAAA for you. I hope this helps!

**Comment by paulbnt23** [comment]
Thanks, this helped a lot.
