### ISSUE TITLE
File openssl_tests.rs has executable permission

### ISSUE THREAD

**Issue by silwol** [bluejekyll/trust-dns#609]
**Describe the bug**
The file `crates/openssl/tests/openssl_tests.rs` has executable permission. This is a potential security problem if it gets included into distribution packages. I found the problem because the Debian lintian tool warns about it.

**To Reproduce**
Run `ls -l crates/openssl/tests/openssl_tests.rs` in the project root, you'll see the -rwxr-xr-x permissions.

**Expected behavior**
Source files should not have executable permissions, they can't be run directly anyway.

**System:**
 - OS: Debian Buster
 - Architecture: x86_64
 - Version trust-dns-openssl 0.4.0
 - rustc version: 1.30

**Additional context:**
I assume it's not possible to update the distributed crate, but it helps to have the permission fixed on the next release.

**Comment by bluejekyll** [comment]
That's strange, don't know how that would have been set, even accidentally.
