### ISSUE TITLE
Query multiple nameservers in parallel

### ISSUE THREAD

**Issue by stuartnelson3** [bluejekyll/trust-dns#612]
**Is your feature request related to a problem? Please describe.**
Querying multiple nameservers in parallel is something done by musl to improve performance, cf. https://wiki.musl-libc.org/functional-differences-from-glibc.html#Name-Resolver/DNS.

My feature request is to allow this functionality.

**Describe the solution you'd like**
Allow setting parallel lookups in ResolverOpts, and limiting the number of parallel lookups at a time. For example, maybe I only want have 3 parallel requests at once (a la musl). Related to #606, I can further say to take the first response that isn't a failure, or if all fail, returning one of those. This requires some thought as a response is then only as fast as it's slowest failure (or timeout).

**Describe alternatives you've considered**
If a SERVFAIL didn't abort trying other nameservers, that would be an alternative, albeit trying requests in serial is not ideal typically.

**Additional context**
See #606

**Comment by bluejekyll** [comment]
FYI, I’ve got a patch coming for #606. This one, we’ll have to consider options on. I think we might want to have a maximum on the number of parallel queries, and default to 2 or so.

**Comment by stuartnelson3** [comment]
Makes sense. It might be easier to say max number of nameservers. If we allow more nameservers than parallel attempts, what is the behavior if all nameservers in the N that get queried fail? Continue trying with the next batch, or fail, and start priority sorting nameservers...

I think musl's policy makes sense: set a max number of nameservers to be queried.

**Comment by stuartnelson3** [comment]
Sounds reasonable to me

**Comment by bluejekyll** [comment]
PR #615 is the current proposed fix for this, I think it's simple enough to incorporate. Right now it defaults to 2 concurrent requests.
