### ISSUE TITLE
trust-dns-proto 0.6 doesn't require recent enough tokio-timer

### ISSUE THREAD

**Issue by seanmonstar** [bluejekyll/trust-dns#638]
**Describe the bug**

Adding `trust-dns-resolver = "0.10"` to a project that already has `tokio-timer = "0.2"` resulted in compile errors of missing imports for `tokio_timer::Timeout`.

Running `cargo update` fixes the issue locally, but publishing a version of my crate could result in others hitting the same issue.

`tokio_timer::Timeout` was introduced in v0.2.6, so that would need to be set as the minimum version of `tokio-timer` in the `Cargo.toml` of `trust-dns-proto`.

**Version:**
Crate: resolver
Version: 0.10.0

**Comment by bluejekyll** [comment]
Is this also true of the recently published 0.10.1?

**Comment by bluejekyll** [comment]
Do you need pre 2.6 to work?

**Comment by seanmonstar** [comment]
No, just reporting that the crate didn't list in its dependencies the minimum version it actually needed. I also needed to update to `tokio-executor = "0.1.4"`.

**Comment by bluejekyll** [comment]
Ok, thanks. I’ll update when I have a chance.

**Comment by bluejekyll** [comment]
Ok, new version published off the r0.10 branch, thanks for reporting this.
