### ISSUE TITLE
Inclusion of "new" record types

### ISSUE THREAD

**Issue by argantos** [bluejekyll/trust-dns#646]
I thought about writing a validator for SSH fingerprints / OPENPGP keys using the [SSHFP](https://en.wikipedia.org/wiki/SSHFP_record) and [OPENPGPKEY](https://tools.ietf.org/html/rfc7929) DNS record types using this awesome project. The former is [commented out](https://github.com/bluejekyll/trust-dns/blob/7c8a0739dad495bf5a4fddfe86b8bbe2aa52d060/crates/proto/src/rr/record_type.rs#L80), and the latter is not present. There may be even more non-omnipresent record types, so I am interested in the criteria when a record type should be included.

In my opinion, DANE methods (most prominentely TLSA) have a huge potential, and it would be nice to see more of them supported.

**Comment by bluejekyll** [comment]
I’ve implemented what I’ve seen as “core” record types. I’m of course open to any standard types.

**Comment by argantos** [comment]
The states of the respective RFCs are "proposed standard" (SSHFP) and "experimental" (OPENPGPKEY). Concerning OPENPGPKEY and other record types I have no strong opinion. Either way, one can always use the Unknown(u16) variant.

But I think SSHFP is ready to be added (it has been around since 2006, and is well-supported in OpenSSH). It was removed in [this commit](https://github.com/bluejekyll/trust-dns/commit/a8fe789836bbd3fb87fe95a1a90c465eb96e1c95#diff-547bf1ddff376596c96285d07bbb1411L38).

**Comment by bluejekyll** [comment]
This was fixed with #647
