### ISSUE TITLE
Log messages at Log level INFO

### ISSUE THREAD

**Issue by alienscience** [bluejekyll/trust-dns#648]
I have been using the Trust DNS client and it has worked perfectly for me -- many thanks.

I integrated the library into an application with the log level set to INFO and have found that the Trust DNS client writes the most log messages -- more than the application and the other libraries:
```
12:29:27 [INFO] sending message via: UDP(8.8.8.8:53)
```
This message is not so useful at the application level -- I know what DNS server I am using. Would it be possible to make this log message in `crates/proto/src/xfer/dns_exchange.rs` DEBUG rather than INFO?

Many thanks for your help.

**Comment by bluejekyll** [comment]
Yes! Absolutely. I definitely don’t want to flood people’s logs ;).

Would you want to submit a pr?

Also, as a workaround with env_logger you can explicitly set trust-dns crates to be warm or error.
