### ISSUE TITLE
Help wanted: Create a trust-dns logo

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#65]

**Comment by naufaal** [comment]
Hi, I graphic designer, I just found your repo about logo. Is this issue still open? I can contribute if possibel. :)

**Comment by bluejekyll** [comment]
Thanks for the interest in this. No, this is not resolved.

I've had some ideas, but have never executed on them myself. To be clear about this, I don't have finances available to this. So picking an openlogos, thanks @soyuka, or a contribution to the project gratis, would be desirable. If you're interested in doing this, @naufaldsg, that would be a wonderful contribution. I'm unfamiliar with attribution for work like this, or licensing...

**Comment by naufaldsg** [comment]
Im bad with coding, but I can contribute like graphics for you. And of course my contribution is for free. You can mention my name on contributor list if possible.

**Comment by bluejekyll** [comment]
https://github.com/bluejekyll/trust-dns/blob/2b17715d6c484848df64e5b350634c4466af7ff6/logo.svg

and on the front page here: https://github.com/bluejekyll/trust-dns/tree/2b17715d6c484848df64e5b350634c4466af7ff6

I'm planning on merging this in, we can replace it. But what I like is the idea of using the bee and it's queen/drone relationship with the hive (DNS). I was wondering if we could do a bee that is like Ferris?
