### ISSUE TITLE
syncrhonous Resolver should maintain conn pool across uses

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#650]
**Is your feature request related to a problem? Please describe.**

See comment: https://github.com/bluejekyll/trust-dns/issues/532#issuecomment-451251197 where the usage of the synchronous Resolver is expected to maintain connections across uses.

**Describe the solution you'd like**

The Global Resolver described in #462 is most-likely the best option. An issue to determine is how to make that programatically configurable.

**Describe alternatives you've considered**

Another option would be to rely on tokio's background processing, but this needs to be researching.

**Additional context**

The synchronous Resolver does not hold a reference to a Tokio runtime, to ensure that it itself is Send/Sync, see documentation here: https://docs.rs/trust-dns-resolver/0.10.2/trust_dns_resolver/struct.Resolver.html

**Comment by bluejekyll** [comment]
FYI @juliangehring

**Comment by bluejekyll** [comment]
Hm, When the decision was made to not carry the old `Tokio::Core` it appeared that there was no way to have a `Send+Sync` syncronous Resolver. This appears to have changed. As tokio::Runtime now appears to be `Send+Sync`. This means it's possible for the Resolver to have a Runtime.

This is probably the easiest patch for the issue.

**Comment by juliangehring** [comment]
Thanks, it works very well now!

**Comment by bluejekyll** [comment]
Thank you for the feedback. It does have a downside of locking between threads on queries, if you share the instance across threads. Just making sure you’re aware of that downside.
