### ISSUE TITLE
Add "NAPTR" RR support

### ISSUE THREAD

**Issue by nhoyle** [bluejekyll/trust-dns#654]
**Is your feature request related to a problem? Please describe.**
trust-dns lacks first-class support for queries for the NAPTR resource record type.

**Describe the solution you'd like**
Implement first-class support for NAPTR.

**Describe alternatives you've considered**
Use "Unknown" query type.

**Additional context**
NAPTR is well established and in wide use (within the context of its intended purpose). It is also a stable specification and a reasonable candidate for direct support.

**Comment by bluejekyll** [comment]
RR specification: https://tools.ietf.org/html/rfc3403
