### ISSUE TITLE
Make tokio optional dependeny for resolver

### ISSUE THREAD

**Issue by fafhrd91** [bluejekyll/trust-dns#658]

**Comment by bluejekyll** [comment]
We can make `tokio` optional, it looks like this will require us to disable the synchronous `Resolver`, but the `AsyncResolver` should be fine. It needs to be a dev dependency for tests. I'm assuming this will be ok?

It will default to on, and will require `default-features=false` on the Cargo.toml dependency line. Sound good?

**Comment by fafhrd91** [comment]
Default is on is totally fine. Thanks!

**Comment by fafhrd91** [comment]
when do you plan to release this feature?

**Comment by bluejekyll** [comment]
I'm planning on releasing 0.11.0-alpha soon. I'm just polishing up some things in another PR that I'd like to land before doing that.

Is this a blocker? I could backport to 0.10 if this is urgent.

**Comment by fafhrd91** [comment]
It is fine. I just need to know timeframe.

**Comment by bluejekyll** [comment]
I can't promise a timeline, but I was hoping to start the next alpha release series in the next week.

**Comment by fafhrd91** [comment]
@bluejekyll when do you plan to release 0.11?

**Comment by bluejekyll** [comment]
I think you mean non-alpha? I would like to publish one more alpha, let that bake a little, and then release 0.11. The next alpha would be in the next week, and that should be the last one, assuming no serious complaints. So maybe 4 weeks?

**Comment by fafhrd91** [comment]
ok, thanks.
