### ISSUE TITLE
Implement DNS over QUIC

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#670]
RFC: https://datatracker.ietf.org/doc/draft-ietf-dprive-dnsoquic/02/

quinn: https://docs.rs/quinn/0.2.0/quinn/

**Comment by LEXUGE** [comment]
AdGuard DNS has supported DoQ https://adguard.com/en/blog/dns-over-quic.html

**Comment by djc** [comment]
Latest version of the spec appears to be here:

https://tools.ietf.org/html/draft-ietf-dprive-dnsoquic-01

**Comment by bluejekyll** [comment]
I just updated the RFC link to the tracker so that it can follow any other forks that happen.
