### ISSUE TITLE
How to send DNS queries in parallel via UDP?

### ISSUE THREAD

**Issue by ovidiu-ionescu** [bluejekyll/trust-dns#736]
I tried to expand on the async DNS query example but the wait time seems to increase linearly with the amount of DNS queries. I get the impression the system is waiting for the first request to get a reply before issuing the second request and so on.

Please provide an example where a number of UDP DNS requests are being submitted without waiting for the server to respond in between.

**Comment by bluejekyll** [comment]
This shouldn’t be the case. Could you share your code?

**Comment by ovidiu-ionescu** [comment]
Here's my code:
https://github.com/ovidiu-ionescu/learning-rust/blob/dns-block/src/dns_resolver.rs

I just took the async example from trust-dns and added a for loop to it.

**Comment by bluejekyll** [comment]
I won’t have time to provide a full example, but your second loop is serializing the futures, what you want is to throw your collection into a select, specifically, `select_all`: https://docs.rs/futures/0.1.26/futures/future/fn.select_all.html

**Comment by ovidiu-ionescu** [comment]
I don't mind waiting for all of them to finish before proceeding, trouble is that one request takes about 20 milliseconds and five take a bit more than 100. I suspect most of that time is actually taken by the packets traveling to Google's DNS and back. I was hoping to get a shorter time overall by sending all the requests at once so that they all travel together and hopefully all five only take a little bit more than just one.

**Comment by bluejekyll** [comment]
In that case, look at https://docs.rs/futures/0.1.26/futures/future/fn.join_all.html, that will combine all the futures and execute them all in parallel. I think it will work better than your loop. You could also configure the resolver to only use tcp, which might provide more reliable performance?

**Comment by bluejekyll** [comment]
It might be good to make sure we're both on the same page in our understanding of futures in Rust. Futures are lazy, this means they shouldn't start executing before being polled. The futures you're creating should not actually even submit the query until you poll them, that would be the `block_on` call in your code. I used to have some bugs in this area, it can be a subtle mistake, I think they're all cleaned up at this point. The reason the `join_all` I mention above would be better than your loop, is that each of those futures you've created for the query, won't actually start until the `block_on`, which means each is serial and waiting for the previous to execute. With a `join_on`, all the futures will be started and then waited on if that is the thing you are putting into the `block_on`.

That should fix your issue.

**Comment by bluejekyll** [comment]
Also, if you want a recursive stub resolver for queries, I would recommend using the resolver: https://docs.rs/trust-dns-resolver/0.11.0-alpha.3/trust_dns_resolver/

**Comment by ovidiu-ionescu** [comment]
`join_all` did make a difference, I see much better times. 
I also learned that futures are lazy.

A double thank you!
