### ISSUE TITLE
AXFR / TSIG example?

### ISSUE THREAD

**Issue by dsvensson** [bluejekyll/trust-dns#782]
What is the question?
Is there any example of initiating an AXFR from a client with a base64 TSIG key, similar to dig:

    dig @::1 +tcp -y hmac-sha256:foo.key:QQ== foo.bar. axfr

Can't figure out how to create the signer. Using featureset:

    trust-dns = { version = "0.16.0", default-features = false, features = ["dns-over-rustls"] }

**Comment by dsvensson** [comment]
Missing due to #14?

**Comment by bluejekyll** [comment]
Yeah, TSIG is not yet implemented. I currently don’t have a need for it, but if someone wanted to go through the ( shakily I think is significant) effort of supporting it, I’d be happy to accept a PR.

**Comment by darnuria** [comment]
Hello, would try to work on axfr with TSIG for the auth, if it's not already done. Checked there is some groundwork in dnssec client (like constant time check) already there. :)
