### ISSUE TITLE
Version numbers need updating post  #778

### ISSUE THREAD

**Issue by rjloura** [bluejekyll/trust-dns#783]
**Describe the bug**
The issue in #778 is resolved in the proto crate but the resolver crate still points to an old version of the proto crate. 

**To Reproduce**
Same as #778 

**Expected behavior**
Clean build

**System:**
- OS: [e.g. smartos]
- Architecture: [e.g. x86_64]
- Version [e.g. joyent_20190228T233723Z trunk]
- rustc version: [e.g. 1.33]

**Version:**
Crate: [e.g. resolver, proto]
Version: [e.g. 0.11.0]

**Additional context**
Bump to 0.7.4: https://github.com/bluejekyll/trust-dns/blob/master/crates/resolver/Cargo.toml#L77
Bump to 0.11.1: https://github.com/bluejekyll/trust-dns/blob/master/crates/resolver/Cargo.toml#L3
probably bump this as well: https://github.com/bluejekyll/trust-dns/blob/master/crates/https/Cargo.toml#L60

**Comment by bluejekyll** [comment]
We need a new release of the proto crate. I can look into doing that later today.

**Comment by bluejekyll** [comment]
this should be good now.

**Comment by rjloura** [comment]
Confirmed trust-dns-resolver 0.11.1 now compiles without issue on smartos.  Thanks!
