### ISSUE TITLE
Include LICENSE-* files in all sub-crates

### ISSUE THREAD

**Issue by ignatenkobrain** [bluejekyll/trust-dns#785]
Just a symlink should be enough for cargo to pick it up when publishing on crates.io.

I believe that this is requirement of Apache-2.0. This would help me to package trust-dns stuff in Fedora.

Thanks!

**Comment by bluejekyll** [comment]
what's the priority for this? i.e. is this blocking and needs a release, or better for compliance?

**Comment by ignatenkobrain** [comment]
Release is appreciated, but definitely not required. As long as you plan to do any release within next few months, I can wait :)

**Comment by bluejekyll** [comment]
Fixed in #832
