### ISSUE TITLE
Refactor with new futures APIs (async/await)

### ISSUE THREAD

**Issue by zonyitoo** [bluejekyll/trust-dns#850]
**Is your feature request related to a problem? Please describe.**
Since `async`/`await` syntax is now in nightly, we should start migrating to the latest futures APIs.

**Describe the solution you'd like**
Migrate all APIs to use `std::Future` (or `tokio::future::Future`).

**Additional context**
Tracking Issue: https://github.com/rust-lang/rust/issues/50547

**Comment by bluejekyll** [comment]
See #849 which is a work in progress. I’m starting with proto and then going to move up to the higher level crates. There’s a lot of changes needed...

**Comment by zonyitoo** [comment]
Cool. I will close this issue then.
