### ISSUE TITLE
master zone record parser currently contains `unimplemented!` these should be removed

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#917]
**Describe the bug**

Will cause ugly failures on named startup. 

see `master.rs`, `crates/client/src/serialize/txt/rdata_parsers/null.rs`, `crates/server/src/store/forwarder/authority.rs`

**Comment by koenw** [comment]
I believe this issue can be closed. The named files don't contain `unimplemented!` (anymore), and the only `unimplemented!` I could find in the project has nothing to do with parsing.

**Comment by bluejekyll** [comment]
Thanks for reviewing that!
