### ISSUE TITLE
Async_std support

### ISSUE THREAD

**Issue by Softsapiens** [bluejekyll/trust-dns#926]
Hi all!
I would like to know if there is any option to decouple trust-dns-resolver from tokio in order to use async_std as executor runtime, or at least, if there are plans for making easy that integration, perhaps using trust-dns-client ClientFuture.

I have tried to use the AsyncResolver spwaned on async_std::task but I get the same situation as is https://github.com/bluejekyll/trust-dns/issues/905

Thanks an advance, and thanks for such a great library.

**Comment by bluejekyll** [comment]
Currently this is being worked on, though it is something that we could work towards. #913 removes all background spawns in from the Resolver (I'm working on the last few changes there).

No, don't just use the ClientFuture, as that is not a Resolver, and won't serve those needs properly.

After #913, there will be a lot of additional work to allow for alternative async UDP, TCP, TLS, and HTTPS implementations to be supported. All of this is of course possible, but that will require a bunch of investigation. There are many good reasons to do this work, beyond supporting `async-std`, which include making the library more usable on new operating systems and such. So this is definitely something we should do.

**Comment by Softsapiens** [comment]
Thanks

**Comment by bluejekyll** [comment]
We can leave this issue open as a tracking issue, and discussion.

**Comment by bluejekyll** [comment]
FYI, with #935 landed, this is something we could start work on.

**Comment by bluejekyll** [comment]
I'm not sure if we can do this (easily) before AsyncRead and AsyncWrite are common between Futures, Tokio and async-std. But the work I believe is basically implementing a new ConnectionProvider for async-std:

https://github.com/bluejekyll/trust-dns/blob/4e917863888bf2b371bff191ffe91a946e7b60fc/crates/resolver/src/name_server/connection_provider.rs#L46-L56

**Comment by bluejekyll** [comment]
With #975 done, I think this should be fairly straight forward at this point.

**Comment by belak** [comment]
I believe this will also require changes in the lower level libraries for the different TLS implementations as well.

**Comment by bluejekyll** [comment]
Most likely. But that doesn’t need to be part of an MVP.
