### ISSUE TITLE
Cannot compile trust-dns-proto v0.18.0-alpha.1

### ISSUE THREAD

**Issue by ebroto** [bluejekyll/trust-dns#931]
First of all, thanks for these awesome crates!

While trying to build the resolver lib as a dependency, I'm getting the following error:
```
   Compiling trust-dns-proto v0.18.0-alpha.1
error[E0432]: unresolved import `tokio_net::tcp`
   --> /home/ebroto/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.18.0-alpha.1/src/tcp/tcp_client_stream.rs:128:16
    |
128 | use tokio_net::tcp::TcpStream as TokioTcpStream;
    |                ^^^ could not find `tcp` in `tokio_net`

error[E0432]: unresolved import `tokio_net::udp`
   --> /home/ebroto/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.18.0-alpha.1/src/udp/udp_stream.rs:316:5
    |
316 | use tokio_net::udp;
    |     ^^^^^^^^^^^^^^ no `udp` in the root

error: aborting due to 2 previous errors
```

It seems to be related to the release of tokio 0.2.0. Yesterday it was building fine.

**Comment by bluejekyll** [comment]
Yes, I have a local branch I'm working on right now for this.

**Comment by bluejekyll** [comment]
There are a lot of changes since the last alpha... btw, this might take me a little bit.

**Comment by bluejekyll** [comment]
waiting on this to be merged and released, it's blocking this change: https://github.com/tokio-rs/tokio/pull/1826

**Comment by encombhat** [comment]
It is already merged BTW

**Comment by bluejekyll** [comment]
thanks, tokio 0.2.1  was just published. I'll have master up to date soon, and then can publish 0.18.0-alpha.2 as well.

**Comment by bluejekyll** [comment]
this is taking a little longer than anticipated. tokio change a few things that have broken different components of the system.

**Comment by bluejekyll** [comment]
Ok, #932 should work for most cases, but before it can be merged with need `tokio-rustls` to be updated.

**Comment by ebroto** [comment]
Thanks for all the work!
