### ISSUE TITLE
Create a test mod for trust-dns-proto

### ISSUE THREAD

**Issue by chunyingw** [bluejekyll/trust-dns#934]
What is the question?
Hey Ben,

Do you have any concern if I create a test mod for trust-dns-proto and move udp and tcp tests into this mod?  I would like to abstract some common setup function and make them public. Ex `pub fn udp_stream_test<S: UdpSocket + Send + 'static, E: crate::Executor>(server_addr: IpAddr, mut exec: E)`.  The benefit is that I could run the same tests using different executor on different platforms like Fuchsia w/o copying/pasting the codes.

Technically the test mod is not required, but I thought it is cleaner to put them into a separate mod. The PR will be based on the current `update to tokio 0.2 release #932`. What's  your opinion?

A headsup, I will create a PR which makes trust-dns-resolver generic for tcp and udp flow soon, so that this crate will be compatible with Fuchsia. Thanks!

**Comment by bluejekyll** [comment]
This sounds good.

 Btw, I’m currently working on a bug cleanup to remove all implicit spawns from the library.  #913 was the initial pass, but after some feedback, I’m working on a different iteration with ’background’ exposed to library consumers. You might be interested in that. (Should make porting to different executors easier).
