### ISSUE TITLE
Make tokio crate optional for trust-dns-proto

### ISSUE THREAD

**Issue by chunyingw** [bluejekyll/trust-dns#958]
Hey Ben,

It seems Fuchsia prefers to make the tokio crate optional. I am taking the effort to make that happen for trust-dns-proto by moving from
1. tokio::io::{AsyncRead, AsyncWrite} to std::io::{AsyncRead, AsyncWrite}
2. Abstract tokio::time::{Timeout, Delay}.

So far I am able to build/run/test trust-dns-proto successfully and run the unit tests using Fuchsia's timer, executor on Fuchsia successfully.

I am going to modify other crates which are impacted because of the interface changes.
Does it sound okay for you?

**Comment by bluejekyll** [comment]
> I am going to modify other crates which are impacted because of the interface changes.
Does it sound okay for you?

Yes, though:

> std::io::{AsyncRead, AsyncWrite}

I think you mean `futures::io::{AsyncRead, AsyncWrite}`, as there aren't std definitions for these. I didn't realize those worked with Tokio already. That's great news.

> So far I am able to build/run/test trust-dns-proto successfully and run the unit tests using Fuchsia's timer, executor on Fuchsia successfully.

That's fantastic!

**Comment by chunyingw** [comment]
> > I am going to modify other crates which are impacted because of the interface changes.
> > Does it sound okay for you?
> 
> Yes, though:
> 
> > std::io::{AsyncRead, AsyncWrite}
> 
> I think you mean `futures::io::{AsyncRead, AsyncWrite}`, as there aren't std definitions for these. I didn't realize those worked with Tokio already. That's great news.
You are absolutely right. It's it's futures:io::{AsyncRead, AsyncWrite}. I use a new type like DnsTokioTcpStream(TokioTcpStream) to achieve this. It's not transparent. 
> 
> > So far I am able to build/run/test trust-dns-proto successfully and run the unit tests using Fuchsia's timer, executor on Fuchsia successfully.
> 
> That's fantastic!
