### ISSUE TITLE
spin transitive dependency is no longer maintained

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/trust-dns#963]
This is currently causing `cargo audit` to fail.

See: https://github.com/briansmith/ring/issues/921

And the advisory: https://rustsec.org/advisories/RUSTSEC-2019-0031

**Comment by djc** [comment]
Note that there's a new (semver-incompatible) spin release, from a new maintainer. So that maybe picked up by *ring*.

**Comment by bluejekyll** [comment]
If that’s the case, then we can remove the explicit allow here: https://github.com/bluejekyll/trust-dns/blob/main/Makefile.toml#L271

**Comment by djc** [comment]
See also https://github.com/briansmith/ring/pull/1053, https://github.com/mvdnes/spin-rs/issues/79, https://github.com/RustSec/advisory-db/pull/424.

**Comment by trinity-1686a** [comment]
`--ignore=RUSTSEC-2019-0031` was removed from Makefile.toml when treating unrelated audit issue in 6cbc7f588641816cb82307e5e37947ba3aa2b8c7

**Comment by bluejekyll** [comment]
Thanks for following up!
