### ISSUE TITLE
crate `log` version 0.4.10 

### ISSUE THREAD

**Issue by chunyingw** [bluejekyll/trust-dns#965]
https://crates.io/crates/log  version 0.4.10 is yanked, should we downgrade the version number to 0.4.8 in Cargo.toml?

**Comment by bluejekyll** [comment]
Yes! I didn't notice that. I wonder if there's a way to check for that in our cleanliness tests... I'll check.

**Comment by bluejekyll** [comment]
I'll take care of this. in #959
