### ISSUE TITLE
global_resolver example is broken

### ISSUE THREAD

**Issue by chunyingw** [bluejekyll/trust-dns#971]
**Describe the bug**
I am running the global_resolver example on Linux and Mac, both failed.

**To Reproduce**
$ cargo run --example global_resolver

**Expected behavior**
Print the valid socket address for the hosts.

**System:**
Mac and Linux

**Version:**
Crate: resolver
Version: 0.18.0 Dec 22, 2019

**Additional context**
Here is the output:
```
www.google.com resolved to Err(Custom { kind: AddrNotAvailable, error: "dns resolution error: proto error" })
www.reddit.com resolved to Err(Custom { kind: AddrNotAvailable, error: "dns resolution error: proto error" })
...
```
It fails here 
https://github.com/bluejekyll/trust-dns/blob/master/crates/proto/src/xfer/mod.rs#L240
I see this trace. "unable to enqueue message".
I believe it's broken with the  [Background with generic spawn](https://github.com/bluejekyll/trust-dns/pull/935).

**Comment by bluejekyll** [comment]
Hm, I guess the examples aren't being run under testing properly...
