### ISSUE TITLE
Can `runtime` arguments be made optional?

### ISSUE THREAD

**Issue by dfoxfranke** [bluejekyll/trust-dns#977]
Having to pass a `tokio::runtime::Handle` in order to construct an `AsyncResolver` (or a `TokioConnectionProvider`) is slightly awkward because it means that programs which use `AsyncResolver` can't be written with a main function declared using `#[tokio::main]`. Programs which use `#[tokio::main]` never explicitly construct a tokio runtime and have no means of obtaining a handle to the one that tokio implicitly constructs. Could the `runtime` argument be made `Option`al, such that if `None` is passed then the resolver will just spawn tasks on the default executor using `tokio::spawn()`?

**Comment by bluejekyll** [comment]
I'd consider it. I hate relying on thread local storage for this stuff, it makes testing really difficult. Let me review our options in this area.

It might be that we could pass in a `TokioTlsHandle` that carries no data, and just calls `tokio::spawn`. I think that would be fine. And that could be the default you're looking for.

**Comment by bluejekyll** [comment]
Ok, I think we're going to handle this in the tokio library itself: https://github.com/tokio-rs/tokio/pull/2040

**Comment by bluejekyll** [comment]
FYI, with https://docs.rs/tokio/0.2.8/tokio/runtime/struct.Handle.html#method.current now in Tokio, users should be able to get a handle to the current runtime in a `#[tokio::main]`. I'll add a function for initializing trust-dns-resolver so that the extra code isn't necessary.

**Comment by gzbakku** [comment]
has this problem been resolved 
how to do this??

**Comment by djc** [comment]
I think this has been solved? At least you can in 0.19 instantiate a `TokioAsyncResolver` that doesn't require you to pass in a `Handle`.

**Comment by dfoxfranke** [comment]
Yes, this should be closed with the addition of the `tokio_from_system_conf()` constructor.
