### ISSUE TITLE
Is published version stale? (release of master needed)

### ISSUE THREAD

**Issue by chunyingw** [bluejekyll/trust-dns#985]
**Describe the bug**
I am downloading trust-dns-resolver crate from crates.io which was published 4 days ago. However the loaded crate seem stable, does not contain the PR#979 (merged 6 days ago) nor PR#975 (merged 11 days ago). Is this expected?

**Version:**
Crate: trust-dns-resolver
Version: 0.18.1

**Comment by bluejekyll** [comment]
Yes, that was a patch for a specific bug. It was released out of `releases/0.18` specifically targetting a server issue. Do you need me to release those changes? I need to see if we need to bump to 0.19 or not...

**Comment by chunyingw** [comment]
Yes, please. I am working on porting it into Fuchsia officially.

**Comment by chunyingw** [comment]
I meant `stale` instead of `stable` in the title :)

**Comment by bluejekyll** [comment]
@chunyingw I'm reviewing interfaces, it looks like we have some naming that I want to try and clean up.

**Comment by chunyingw** [comment]
Sure, thanks for cleaning up. I tried the the new version on Fuchsia, it works well.

**Comment by bluejekyll** [comment]
FYI. On that PR, I want to drop the usage of `failure` and convert to `thiserror`, if it’s not a ton of work. Do you have any issue with that?

**Comment by bluejekyll** [comment]
Now’s a good time to do that since I have to bump to 0.19 anyway.

**Comment by chunyingw** [comment]
It is great. No issue for me. We dropped failure on Fuchsia a couple of
weeks ago.

**Comment by bluejekyll** [comment]
Got delayed on this over the weekend and yesterday. I'll be pushing a new release later today.

**Comment by chunyingw** [comment]
Cool, thx.

**Comment by bluejekyll** [comment]
0.19.0 was published: https://crates.io/crates/trust-dns-resolver/0.19.0

**Comment by chunyingw** [comment]
Thanks. I tried it out on Fuchsia. trust-dns-proto is good to go. 
However because the way trust-dns-resolver Cargo.toml file is written, by default the tokio-runtime feature of trust-dns-proto is enabled, so it is pulling down tokio crates as well, which is not good. I need to solve this issue before I can port trust-dns-resolver to Fuchsia.

**Comment by bluejekyll** [comment]
Ok. I think changeling the dependency from resolver to proto to pull proto with no default features would fix that, right?

**Comment by chunyingw** [comment]
Yes that is what I am thinking as well. I will work on that tomorrow.
